pins:
    - id: E2
      class: outputs
      ts_name: Fan Relay (E2)
    - id: E3
      class: outputs
      ts_name: Fuel Relay (E3)
    - id: E4
      class: switch_inputs
      ts_name: Launch Control (E4)
    - id: E5
      class: outputs
      ts_name: Tachometer (E5)
    - id: [E6, E6]
      class: [switch_inputs, event_inputs]
      ts_name: Camshaft Input (E6)
    - id: [C13, C13]
      class: [switch_inputs, event_inputs]
      ts_name: CrankShaft Input (C13)
    - id: EFI_ADC_0
      class: analog_inputs
      ts_name: Battery Reference Input (A0)
    - id: [A1, EFI_ADC_1]
      class: [switch_inputs, analog_inputs]
      ts_name: TPS Reference Input (A1)
    - id: EFI_ADC_2
      class: analog_inputs
      ts_name: CLT Reference Input (A2)
    - id: EFI_ADC_3
      class: analog_inputs
      ts_name: IAT Reference Input (A3)
    - id: EFI_ADC_4
      class: analog_inputs
      ts_name: O2 Reference Input (A4)
    - id: EFI_ADC_14
      class: analog_inputs
      ts_name: Fuel Pressure Reference Input (C4)
    - id: EFI_ADC_15
      class: analog_inputs
      ts_name: Oil Pressure Reference Input (C5)
    - id: EFI_ADC_8
      class: analog_inputs
      ts_name: MAP Pressure Reference Input (B0)
    - id: EFI_ADC_9
      class: analog_inputs
      ts_name: BARO Pressure Reference Input (B1)
    - id: E8
      class: outputs
      ts_name: Injector 8 Output (E8)
    - id: E9
      class: outputs
      ts_name: Injector 7 Output (E9)
    - id: E10
      class: outputs
      ts_name: Injector 6 Output (E10)
    - id: E11
      class: outputs
      ts_name: Injector 5 Output (E11)
    - id: E12
      class: outputs
      ts_name: Injector 4 Output (E12)
    - id: E13
      class: outputs
      ts_name: Injector 3 Output (E13)
    - id: E14
      class: outputs
      ts_name: Injector 2 Output (E14)
    - id: E15
      class: outputs
      ts_name: Injector 1 Output (E15)
    - id: E1
      class: switch_inputs
      ts_name: Clutch Input (E1)
    - id: C7
      class: outputs
      ts_name: Boost Controller Output (C7)
    - id: C6
      class: outputs
      ts_name: Idle1 Output (C6)
    - id: D15
      class: outputs
      ts_name: HC1 Output (D15)
    - id: D14
      class: outputs
      ts_name: HC2 Output (D14)
    - id: D13
      class: outputs
      ts_name: Ignition 2 Output (D13)
    - id: D12
      class: outputs
      ts_name: Ignition 1 Output (D12)
    - id: D11
      class: outputs
      ts_name: Ignition 7 Output (D11)
    - id: D10
      class: outputs
      ts_name: Ignition 8 Output (D10)
    - id: D9
      class: outputs
      ts_name: Ignition 6 Output (D9)
    - id: D8
      class: outputs
      ts_name: Ignition 5 Output (D8)
    - id: B15
      class: outputs
      ts_name: Ignition 3 Output (B15)
    - id: B14
      class: outputs
      ts_name: Ignition 4 Output (B14)
