pins:
  - pin: U7
#H144_IN_RES2
    id: F10
    class: switch_inputs
    ts_name: C1-7 Stop/Brake Pedal
    function: Stop/Brake Pedal switch input
    type: din

  - pin: U12
    # H144_OUT_IO11
    id: G2
    class: outputs
    function: MIL Check Engine
    type: hs
    ts_name: C1-12 Check Engine

  - pin: U13
    # H144_OUT_IO5
    id: D2
    class: outputs
    function: Fuel Pump Relay Output
    type: hs
    ts_name: C1-13 - Fuel Pump

  - pin: U14
    function: stm32 BOOT

  - pin: U19
# H144_IN_VBATT
    id: EFI_ADC_5
    class: analog_inputs
    function: +12V
    ts_name: C1-19 Battery Sense
    type: 12v

  - pin: U25
    # H144_OUT_PWM7
    id: D15
    class: outputs
    function: Tachometer Output
    type: hs
    ts_name: C1-25 Tach

  - pin: U26
    # H144_OUT_IO6
    id: G11
    class: outputs
    ts_name: C1-26 - Starter Relay
    function: Starter Relay
    type: ls
    color: purple

  - pin: U39
    # H144_OUT_PWM6
    id: D14
    class: outputs
    ts_name: C1-39 - VSS Output
    function: VSS Output
    type: hs
    color: purple

  - pin: U40
    # H144_OUT_IO3
    id: G14
    class: outputs
    ts_name: C1-40 - MAIN
    function: Main relay control
    type: ls
    color: purple

  - pin: U44
    # H144_IN_CRANK_ANALOG
    id: EFI_ADC_9
    class: analog_inputs
    function: Primary Fuel Level
    ts_name: C1-44 Primary Fuel Level

  - pin: U45
    # H144_IN_CAM_ANALOG
    id: EFI_ADC_6
    class: analog_inputs
    function: Secondary Fuel Level
    ts_name: C1-45 Secondary Fuel Level

  - pin: U46
    # H144_IN_AUX3
    id: EFI_ADC_15
    class: analog_inputs
    function: Vac Sense
    ts_name: C1-46 Vac Sense

  - pin: U47
    # H144_IN_PPS
    id: EFI_ADC_3
    class: analog_inputs
    ts_name: C1-47 - PPS1
    function: PPS1 analog input
    type: av

  - pin: U49
    # H144_IN_AUX2
    id: EFI_ADC_14
    class: analog_inputs
    ts_name: C1-49 - PPS2
    function: PPS2 analog input
    type: av

  - pin: U56
    # H144_OUT_IO8
    id: G4
    class: outputs
    ts_name: C1-56 - Starter Enable
    function: Starter Enable
    type: ls
    color: purple

info:
  title: Hellen GM E67
  name: Hellen GM E67
  board_url: https://rusefi.com/s/gm-e67
  image:
    file: main.jpg
  pins:
    - pin: U12
      x: 1119
      y: 424

    - pin: U19
      x: 1095
      y: 234

