meta: config/boards/hellen_mm100_meta.h

pins:
  - pin: 1A
    id: TLE9104_0_OUT_3
    function: Injector 4 Output
    class: outputs
    type: ls
    ts_name: ___ - Injector 4
    color: blue

  - pin: 2A
    id: TLE9104_0_OUT_2
    function: Injector 3 Output
    class: outputs
    type: ls
    ts_name: ___ - Injector 3
    color: blue

  - pin: 3A
    id: TLE9104_0_OUT_1
    function: Injector 2 Output
    class: outputs
    type: ls
    ts_name: ___ - Injector 2
    color: blue

  - pin: 4A
    id: TLE9104_0_OUT_0
    function: Injector 1 Output
    class: outputs
    type: ls
    ts_name: ___ - Injector 1
    color: blue

  - pin: 5A
    id: TLE9104_1_OUT_1
    function: Fuel Pump Relay
    class: outputs
    type: ls
    ts_name: ___ Fuel Pump Relay
    color: blue

  - pin: 6A
    id: TLE9104_1_OUT_2
    function: Idle Output
    class: outputs
    type: ls
    ts_name: ___ Idle Output
    color: blue

  - pin: 14A
    id: TLE9104_1_OUT_0
    function: Tach Out
    class: outputs
    type: ls
    ts_name: ___ Tach Output
    color: blue

  - pin: 18A
    meta: MM100_IN_TPS_ANALOG
    class: analog_inputs
    function: TPS Sensor Input
    ts_name: ___ - TPS
    type: av
    color: orange


  - pin: 19A
    meta: MM100_IN_CLT_ANALOG
    class: analog_inputs
    function: CLT Sensor Input
    ts_name: ___ - CLT
    type: av
    color: grey


  - pin: 20A
    meta: MM100_IN_IAT_ANALOG
    class: analog_inputs
    function: IAT Sensor Input
    ts_name: ___ - IAT
    color: blue

  - pin: On-board MAP
    meta: MM100_IN_MAP2_ANALOG
    class: analog_inputs
    function: MAP Sensor Input
    ts_name: On-board MAP
    color: orange

  - pin: 21A
    meta: MM100_IN_MAP1_ANALOG
    class: analog_inputs
    function: MAP Sensor Input
    ts_name: ___ - MAP
    type: av
    color: yellow


  - pin: 23A
    function: Sensor +5v Power Feed
    type: 5v
    color: orange


  - pin: 26A
    function: Power Ground
    type: gnd
    color: black
  - pin: 27A
    function: Power Ground
    type: gnd
    color: black


  - pin: 28A
    id: TLE9104_1_OUT_3
    function: Fan Relay
    class: outputs
    type: ls
    ts_name: ___ Fan Relay
    color: blue

info:
  cid: main
  title: AlphaX Silver
  name: AlphaX Silver
  board_url: https://rusefi.com/s/silver
  directory: hellen/alphax-silver
  image:
    file: 34pins-3k.jpg
  pins:
    - pin: 1A
      x: 95
      y: 90
    - pin: 2A
      x: 120
      y: 90
    - pin: 3A
      x: 155
      y: 90
    - pin: 4A
      x: 180
      y: 90
    - pin: 5A
      x: 205
      y: 90
    - pin: 6A
      x: 230
      y: 90
    - pin: 7A
      x: 255
      y: 90
    - pin: 8A
      x: 280
      y: 90
    - pin: 9A
      x: 305
      y: 90
    - pin: 10A
      x: 110
      y: 120
    - pin: 11A
      x: 135
      y: 120
    - pin: 12A
      x: 160
      y: 120
    - pin: 13A
      x: 185
      y: 120
    - pin: 14A
      x: 210
      y: 120
    - pin: 15A
      x: 235
      y: 120
    - pin: 16A
      x: 260
      y: 120
    - pin: 17A
      x: 285
      y: 120
    - pin: 18A
      x: 110
      y: 150
    - pin: 19A
      x: 135
      y: 150
    - pin: 20A
      x: 160
      y: 150
    - pin: 21A
      x: 185
      y: 150
    - pin: 22A
      x: 210
      y: 150
    - pin: 23A
      x: 235
      y: 150
    - pin: 24A
      x: 260
      y: 150
    - pin: 25A
      x: 285
      y: 150
    - pin: 26A
      x: 95
      y: 180
    - pin: 27A
      x: 120
      y: 180
    - pin: 28A
      x: 155
      y: 180
    - pin: 29A
      x: 180
      y: 180
    - pin: 30A
      x: 205
      y: 180
    - pin: 31A
      x: 230
      y: 180
    - pin: 32A
      x: 255
      y: 180
    - pin: 33A
      x: 280
      y: 180
    - pin: 34A
      x: 305
      y: 180
