meta: config/boards/hellen_meta.h

pins:
  - pin: 1A
    id: TLE9104_0_OUT_3
    function: Injector 4 Output
    class: outputs
    type: inj
    ts_name: ___ - Injector 4
    color: blue

  - pin: 2A
    id: TLE9104_0_OUT_2
    function: Injector 3 Output
    class: outputs
    type: inj
    ts_name: ___ - Injector 3
    color: blue

  - pin: 3A
    id: TLE9104_0_OUT_1
    function: Injector 2 Output
    class: outputs
    type: inj
    ts_name: ___ - Injector 2
    color: blue

  - pin: 4A
    id: TLE9104_0_OUT_0
    function: Injector 1 Output
    class: outputs
    type: inj
    ts_name: ___ - Injector 1
    color: blue

  - pin: 5A
    id: TLE9104_1_OUT_1
    function: Fuel Pump Relay
    class: outputs
    type: inj
    ts_name: ___ Fuel Pump Relay
    color: blue

  - pin: 6A
    id: TLE9104_1_OUT_2
    function: Idle Output
    class: outputs
    type: inj
    ts_name: ___ Idle Output
    color: blue

  - pin: 28A
    id: TLE9104_1_OUT_3
    function: Fan Realy
    class: outputs
    type: inj
    ts_name: ___ Fan Realy
    color: blue

info:
  cid: main
  title: AlphaX Silver
  name: AlphaX Silver
  board_url: https://rusefi.com/s/silver
  image:
    file: 34pins-3k.jpg
  pins:
    - pin: 1A
      x: 95
      y: 90
    - pin: 2A
      x: 120
      y: 90
    - pin: 3A
      x: 155
      y: 90
    - pin: 4A
      x: 180
      y: 90
    - pin: 5A
      x: 205
      y: 90
    - pin: 6A
      x: 230
      y: 90
    - pin: 7A
      x: 255
      y: 90
    - pin: 8A
      x: 280
      y: 90
    - pin: 9A
      x: 305
      y: 90
    - pin: 10A
      x: 110
      y: 120
    - pin: 11A
      x: 135
      y: 120
    - pin: 12A
      x: 160
      y: 120
    - pin: 13A
      x: 185
      y: 120
    - pin: 14A
      x: 210
      y: 120
    - pin: 15A
      x: 235
      y: 120
    - pin: 16A
      x: 260
      y: 120
    - pin: 17A
      x: 285
      y: 120
    - pin: 18A
      x: 110
      y: 150
    - pin: 19A
      x: 135
      y: 150
    - pin: 20A
      x: 160
      y: 150
    - pin: 21A
      x: 185
      y: 150
    - pin: 22A
      x: 210
      y: 150
    - pin: 23A
      x: 235
      y: 150
    - pin: 24A
      x: 260
      y: 150
    - pin: 25A
      x: 285
      y: 150
    - pin: 26A
      x: 95
      y: 180
    - pin: 27A
      x: 120
      y: 180
    - pin: 28A
      x: 155
      y: 180
    - pin: 29A
      x: 180
      y: 180
    - pin: 30A
      x: 205
      y: 180
    - pin: 31A
      x: 230
      y: 180
    - pin: 32A
      x: 255
      y: 180
    - pin: 33A
      x: 280
      y: 180
    - pin: 34A
      x: 305
      y: 180
