pins:
  - pin: A1
    class: outputs
    function: Injector 3 Positive
  - pin: A2
    class: outputs
    function: Injector 4 Positive
  - pin: A3
    class: outputs
    function: Injector 2 Negative

  - pin: A5
    function: WBO Heater

  - pin: A14
    class: outputs
# 2013 kia
    function: Fan Relay High
    type: ls

  - pin: A15
    class: outputs
    function: Exhaust VVT Solenoid
    type: ls

  - pin: A16
    class: outputs
    function: Injector 2 Positive
  - pin: A17
    class: outputs
    function: Injector 1 Positive
  - pin: A18
    class: outputs
    function: Injector 3 Negative

  - pin: A20
    function: Downstream O2 Heater


  - pin: A23
    class: analog_inputs
    function: CLT Coolant Temperature Signal
  - pin: A24
    function: CLT Coolant Ground
    type: gnd
    color: brown

  - pin: A26
    class: analog_inputs
    function: Fuel Tank Pressure Signal

  - pin: A27
    ts_name: A27 Fuel Pump Control
    function: LP Fuel Pump Control w/o smart key (use R1)
    class: outputs
    type: ls

  - pin: A29
    class: outputs
# veloster
    function: A/C Relay Output
    type: ls

  - pin: A31
    class: outputs
    function: Coil 3
  - pin: A32
    class: outputs
    function: Coil 1
  - pin: A33
    class: outputs
    function: Injector 1 Negative

  - pin: A34
    class: outputs
    function: HPFP High Fuel Pressure Valve Positive

  - pin: A35
    class: outputs
    ts_name: ETB_OUT-
    function: -ETB_OUT DC Motor

  - pin: A37
    function: Knock Signal
  - pin: A38
    function: Knock Ground
    type: gnd


  - pin: A40
    function: Stop Lamp Switch 12v

  - pin: A45
    class: outputs
    function: Intake VVT Solenoid
    type: ls
  - pin: A46
    class: outputs
    function: Coil 4
  - pin: A47
    class: outputs
    function: Coil 2
  - pin: A48
    class: outputs
    function: Injector 4 Negative

  - pin: A49
    class: outputs
    function: HPFP High Fuel Pressure Valve Negative

  - pin: A50
    class: outputs
    ts_name: ETB_OUT+
    function: +ETB_OUT DC Motor

  - pin: A53
    function: Brake Test Switch 12v


  - pin: A55
    function: Clutch Input


  - pin: A57
    function: Alternator COM
  - pin: A58
    class: outputs
    function: Tach Output
  - pin: A59
    class: outputs
    function: Cooling Fan PWM Output

  - pin: A60
    class: outputs
    function: VIS Control

  - pin: K1
    function: Power GND
    type: gnd
  - pin: K2
    function: Power GND
    type: gnd
  - pin: K3
    function: Power GND
    type: gnd

  - pin: K4
    function: +12V from main relay 20A
    type: 12v
    color: red
  - pin: K5
    function: Constant Battery Power
    type: 12v
  - pin: K6
    function: Constant Battery Power
    type: 12v
  - pin: K7
    function: +12V from main relay
    type: 12v
    color: red

  - pin: K8
    function: Downstream O2 Ground
    type: gnd


  - pin: K9
    function: PPS Pedal Signal No1
    class: analog_inputs


  - pin: K10
    function: PPS Pedal Sensor No2 Ground
    type: gnd

  - pin: K12
    function: Fuel Tank Pressure Sensor Ground
    type: gnd

  - pin: K13
    function: BVS Brake Vacuum Sensor Ground
    type: gnd

  - pin: K14
    class: analog_inputs
    ts_name: --- - TPS1
    function: analog input TPS1
    type: av

  - pin: K17
    function: Fuel Tank Level Sender

  - pin: K18
    function: PPS Pedal Supply +5v No2
  - pin: K19
    function: BVS Booster Vacuum Supply +5v
  - pin: K20
    function: APT/RPS Supply +5v

  - pin: K21
    function: ISG Switch

  - pin: K22
    function: Wiper Switch Input Active High
  - pin: K23
    function: Neutral Switch
  - pin: K24
    function: Alternator PWM Control

  - pin: K27
    function: ISG Switch Indicator
  - pin: K29
    # VIGN PA5
    id: EFI_ADC_5
    class: analog_inputs
    ts_name: Ignition Key Voltage
    function: +12V engine ECU power source, run/start

  - pin: K30
    function: Downstream O2 Signal



  - pin: K31
    function: PPS Pedal Signal No2
    class: analog_inputs

  - pin: K32
    function: PPS Pedal Sensor No1 Ground
    type: gnd
    color: brown

  - pin: K33
    function: ATS Ambient Temperature Sensor Ground
    type: gnd
    color: brown

  - pin: K35
    function: TPS Ground
    type: gnd
    color: brown

  - pin: K36
    class: analog_inputs
    ts_name: --- - TPS2
    function: analog input TPS2
    type: av

  - pin: K37
    function: ATS Ambient Temperature Sensor Signal

  - pin: K39
    function: TPS Supply +5v

  - pin: K40
    function: PPS Pedal Supply +5v No1
  - pin: K41
    function: Map/Fuel Sensor Supply +5v

  - pin: K42
    function: Cam Sensors Supply +5v

  - pin: K43
    function: A/C switch input

  - pin: K44
    function: A/C Pressure Switch (?)
  - pin: K45
    function: A/C Pressure Input
    class: analog_inputs
    type: av
  - pin: K46
    function: VSS Vehicle Speed Signal
  - pin: K47
    function: Start Relay HI Output
  - pin: K50
    function: Check Engine Light
  - pin: K52
    function: WBO Virtual Gnd
  - pin: K53
    function: WBO Pumping Current

  - pin: K55
    function: Boost Pressure Ground
    type: gnd
    color: brown

  - pin: K57
    class: analog_inputs
    function: Boost Pressure Signal

  - pin: K58
    class: analog_inputs
    function: High Fuel Pressure Signal

  - pin: K60
    function: Start Request

  - pin: K61
    function: LIN bus

  - pin: K62
    function: CAN bus No2 low UNUSED?
    type: can
  - pin: K63
    function: CAN bus low
    type: can

  - pin: K64
    function: Exhaust Cam Ground
    type: gnd
    color: brown

  - pin: K65
    function: Exhaust Cam Signal

  - pin: K67
    function: Crank Ground VR Negative

  - pin: K72
    function: Purge Valve Solenoid Low
    class: outputs
    type: ls

  - pin: K74
    function: WBO Nerst
  - pin: K75
    function: WBO Trim

  - pin: K76
    function: High Pressure Fuel Sensor Ground
    type: gnd
    color: brown

  - pin: K77
    function: A/C Pressure Ground
    type: gnd
    color: brown

  - pin: K78
    type: gnd
    function: Map Ground

  - pin: K79
    class: analog_inputs
    function: Intake Air Signal
  - pin: K80
    class: analog_inputs
    function: Map Signal


  - pin: K83
    function: Immo Data

  - pin: K84
    function: CAN bus No2 high UNUSED?
    type: can
  - pin: K85
    function: CAN bus high
    type: can

  - pin: K86
    function: Intake Cam Ground
    type: gnd
    color: brown

  - pin: K87
    function: Intake Cam Signal

  - pin: K89
    function: Crank Signal VR Positive

  - pin: K90
    ts_name: K90 Fuel Pump Control
    function: LP Fuel Pump Control w smart key (use R2)
    class: outputs
    type: ls

  - pin: K92
    ts_name: Wastegate Valve Solenoid
    function: Wastegate Valve Solenoid
    class: outputs
    type: ls

  - pin: K93
    class: outputs
    ts_name: Main Relay
    function: Main Relay Control
    type: ls

  - pin: K94
    function: Starter Relay
    class: outputs
    type: ls


info:
  board_url: https://wiki.rusefi.com/Hellen-Hyundai-PB
  cid: main
  directory: hellen/hellen-hyundai-pb-mt
  title: Hellen Hyundai PB MT
  image:
    file: main.jpg
  pins:
    - pin: K1
      x: 1900
      y: 660
    - pin: K2
      x: 2055
      y: 660

    - pin: K3
      x: 1900
      y: 458
    - pin: K4
      x: 2055
      y: 458

    - pin: K5
      x: 1900
      y: 259
    - pin: K6
      x: 2055
      y: 259

    - pin: K7
      x: 2251
      y: 660
    - pin: K8
      x: 2340
      y: 660
    - pin: K9
      x: 2412
      y: 660
    - pin: K10
      x: 2492
      y: 660
    - pin: K11
      x: 2566
      y: 660
    - pin: K12
      x: 2633
      y: 660
    - pin: K13
      x: 2714
      y: 660
    - pin: K14
      x: 2791
      y: 660
    - pin: K15
      x: 2865
      y: 660
    - pin: K16
      x: 2940
      y: 660
    - pin: K17
      x: 3011
      y: 660
    - pin: K18
      x: 3086
      y: 660
    - pin: K19
      x: 3161
      y: 660
    - pin: K20
      x: 3235
      y: 660
    - pin: K21
      x: 3314
      y: 660
    - pin: K22
      x: 3386
      y: 660
    - pin: K23
      x: 3458
      y: 660
    - pin: K24
      x: 3530
      y: 660
    - pin: K25
      x: 3605
      y: 660
    - pin: K26
      x: 3681
      y: 660
    - pin: K27
      x: 3754
      y: 660
    - pin: K28
      x: 3827
      y: 660




    - pin: K29
      x: 2251
      y: 571
    - pin: K30
      x: 2340
      y: 571
    - pin: K31
      x: 2412
      y: 571
    - pin: K32
      x: 2492
      y: 571
    - pin: K33
      x: 2566
      y: 571
    - pin: K34
      x: 2633
      y: 571
    - pin: K35
      x: 2714
      y: 571
    - pin: K36
      x: 2791
      y: 571
    - pin: K37
      x: 2865
      y: 571
    - pin: K38
      x: 2940
      y: 571
    - pin: K39
      x: 3011
      y: 571
    - pin: K40
      x: 3086
      y: 571
    - pin: K41
      x: 3161
      y: 571
    - pin: K42
      x: 3235
      y: 571
    - pin: K43
      x: 3314
      y: 571
    - pin: K44
      x: 3386
      y: 571
    - pin: K45
      x: 3458
      y: 571
    - pin: K46
      x: 3530
      y: 571
    - pin: K47
      x: 3605
      y: 571
    - pin: K48
      x: 3681
      y: 571
    - pin: K49
      x: 3754
      y: 571
    - pin: K50
      x: 3827
      y: 571



    - pin: K51
      x: 2251
      y: 342
    - pin: K52
      x: 2340
      y: 342
    - pin: K53
      x: 2412
      y: 342
    - pin: K54
      x: 2492
      y: 342
    - pin: K55
      x: 2566
      y: 342
    - pin: K56
      x: 2633
      y: 342
    - pin: K57
      x: 2714
      y: 342
    - pin: K58
      x: 2791
      y: 342
    - pin: K59
      x: 2865
      y: 342
    - pin: K60
      x: 2940
      y: 342
    - pin: K61
      x: 3011
      y: 342
    - pin: K62
      x: 3086
      y: 342
    - pin: K63
      x: 3161
      y: 342
    - pin: K64
      x: 3235
      y: 342
    - pin: K65
      x: 3314
      y: 342
    - pin: K66
      x: 3386
      y: 342
    - pin: K67
      x: 3458
      y: 342
    - pin: K68
      x: 3530
      y: 342
    - pin: K69
      x: 3605
      y: 342
    - pin: K70
      x: 3681
      y: 342
    - pin: K71
      x: 3754
      y: 342
    - pin: K72
      x: 3827
      y: 342




    - pin: K73
      x: 2251
      y: 258
    - pin: K74
      x: 2340
      y: 258
    - pin: K75
      x: 2412
      y: 258
    - pin: K76
      x: 2492
      y: 258
    - pin: K77
      x: 2566
      y: 258
    - pin: K78
      x: 2633
      y: 258
    - pin: K79
      x: 2714
      y: 258
    - pin: K80
      x: 2791
      y: 258
    - pin: K81
      x: 2865
      y: 258
    - pin: K82
      x: 2940
      y: 258
    - pin: K83
      x: 3011
      y: 258
    - pin: K84
      x: 3086
      y: 258
    - pin: K85
      x: 3161
      y: 258
    - pin: K86
      x: 3235
      y: 258
    - pin: K87
      x: 3314
      y: 258
    - pin: K88
      x: 3386
      y: 258
    - pin: K89
      x: 3458
      y: 258
    - pin: K90
      x: 3530
      y: 258
    - pin: K91
      x: 3605
      y: 258
    - pin: K92
      x: 3681
      y: 258
    - pin: K93
      x: 3754
      y: 258
    - pin: K94
      x: 3827
      y: 258


    - pin: A1
      x: 301
      y: 660
    - pin: A2
      x: 410
      y: 660
    - pin: A3
      x: 520
      y: 660
    - pin: A4
      x: 623
      y: 660
    - pin: A5
      x: 724
      y: 660
    - pin: A6
      x: 815
      y: 660
    - pin: A7
      x: 897
      y: 660
    - pin: A8
      x: 967
      y: 660
    - pin: A9
      x: 1044
      y: 660
    - pin: A10
      x: 1118
      y: 660
    - pin: A11
      x: 1193
      y: 660
    - pin: A12
      x: 1270
      y: 660
    - pin: A13
      x: 1348
      y: 660
    - pin: A14
      x: 1414
      y: 660
    - pin: A15
      x: 1504
      y: 660




    - pin: A16
      x: 301
      y: 577
    - pin: A17
      x: 410
      y: 577
    - pin: A18
      x: 520
      y: 577
    - pin: A19
      x: 623
      y: 577
    - pin: A20
      x: 724
      y: 577
    - pin: A21
      x: 815
      y: 577
    - pin: A22
      x: 897
      y: 577
    - pin: A23
      x: 967
      y: 577
    - pin: A24
      x: 1044
      y: 577
    - pin: A25
      x: 1118
      y: 577
    - pin: A26
      x: 1193
      y: 577
    - pin: A27
      x: 1270
      y: 577
    - pin: A28
      x: 1348
      y: 577
    - pin: A29
      x: 1414
      y: 577
    - pin: A30
      x: 1504
      y: 577



    - pin: A31
      x: 301
      y: 353
    - pin: A32
      x: 410
      y: 353
    - pin: A33
      x: 520
      y: 353
    - pin: A34
      x: 623
      y: 353
    - pin: A35
      x: 724
      y: 353
    - pin: A36
      x: 815
      y: 353
    - pin: A37
      x: 897
      y: 353
    - pin: A38
      x: 967
      y: 353
    - pin: A39
      x: 1044
      y: 353
    - pin: A40
      x: 1118
      y: 353
    - pin: A41
      x: 1193
      y: 353
    - pin: A42
      x: 1270
      y: 353
    - pin: A43
      x: 1348
      y: 353
    - pin: A44
      x: 1414
      y: 353
    - pin: A45
      x: 1504
      y: 353



    - pin: A46
      x: 301
      y: 264
    - pin: A47
      x: 410
      y: 264
    - pin: A48
      x: 520
      y: 264
    - pin: A49
      x: 623
      y: 264
    - pin: A50
      x: 724
      y: 264
    - pin: A51
      x: 815
      y: 264
    - pin: A52
      x: 897
      y: 264
    - pin: A53
      x: 967
      y: 264
    - pin: A54
      x: 1044
      y: 264
    - pin: A55
      x: 1118
      y: 264
    - pin: A56
      x: 1193
      y: 264
    - pin: A57
      x: 1270
      y: 264
    - pin: A58
      x: 1348
      y: 264
    - pin: A59
      x: 1414
      y: 264
    - pin: A60
      x: 1504
      y: 264

