pins:
  - pin: 1
    id: [E11, E11]
    class: [event_inputs, switch_inputs]
    function: Digital trigger/switch input for instance Hall type CAM
    ts_name: Digital 2
    type: din
    color: green

  - pin: 2
    id: [E12, E12]
    class: [event_inputs, switch_inputs]
    function: Digital trigger/switch input for instance VSS
    ts_name: Digital 3
    type: din
    color: white

  - pin: 3
    id: [E14, E14]
    class: [event_inputs, switch_inputs]
    function: Digital trigger/switch input for instance Start Button
    ts_name: Digital 4
    color: grey
    type: din

  - pin: 4
    function: "Variable Reluctance #2 positive"
    type: vr
    color: blue

  - id: E8
    class: event_inputs
    ts_name: VR 2

  - pin: 5
    function: "Variable Reluctance #1 positive"
    type: vr
    color: blue

  - id: E7
    class: event_inputs
    ts_name: VR 1

  - pin: 6
    function: ETB 1 negative
    type: etb
    color: white

  - pin: 7
    function: ETB 1 positive
    type: etb
    color: blue

  - pin: 8
    function: ETB 2 negative
    type: etb
    color: white

  - pin: 9
    id: [E13, E13]
    class: [event_inputs, switch_inputs]
    function: Digital trigger/switch input
    ts_name: Digital 5
    type: din

  - pin: 10
    id: [C6, C6]
    class: [event_inputs, switch_inputs]
    function: Digital trigger/switch input
    ts_name: Digital 1
    type: din
    color: yellow

  - pin: 11
    id: [E15, E15]
    class: [event_inputs, switch_inputs]
    function: Digital trigger/switch input
    ts_name: Digital 6
    type: din

  - pin: 12
    function: "Variable Reluctance #2 negative"
    type: vr
    color: white

  - pin: 13
    function: "Variable Reluctance #1 negative"
    type: vr
    color: white

  - pin: 14
    function: Ground
    type: gnd

  - pin: 15
    function: ETB 2 positive
    type: etb
    color: blue

  - pin: 16
    function: CAN bus low
    color: blue
    type: can

  - pin: 17
    function: CAN bus high
    color: green
    type: can

  - pin: 18
    id: EFI_ADC_7
    class: analog_inputs
    ts_name: Battery Sense
    function: Ignition power / ECU power source. Connect this pin to the output of your ignition switch.
    type: 12v

  - pin: 19
    function: Power GND
    type: gnd

  - pin: 20
    function: Power GND
    type: gnd

  - pin: 21
    function: CAN2 bus low
    type: can
    color: blue

  - pin: 22
    function: CAN2 bus high
    type: can
    color: green

  - pin: 23
    function: Power supply from main relay. Connect this pin to the output of the car's main relay that also powers injectors, coils, etc. Supplies power to electronic throttle drivers and high side outputs.
    type: 12v

  - pin: PD8
    id: D8
    class: outputs
    ts_name: STM32 PD8

  - pin: PD9
    id: D9
    class: outputs
    ts_name: STM32 PD9

  - pin: PD10
    id: D10
    class: outputs
    ts_name: STM32 PD10

  - pin: PD11
    id: D11
    class: outputs
    ts_name: STM32 PD11

  - pin: PD12
    id: D12
    class: outputs
    ts_name: STM32 PD12

  - pin: PD13
    id: D13
    class: outputs
    ts_name: STM32 PD13

info:
  title: Proteus
  name: Black23
  board_url: "https://github.com/rusefi/rusefi/wiki/Proteus-Manual"
  directory: proteus
  cid: black23
  image:
    file: black23.jpg
  pins:
    - pin: 1
      x: 239
      y: 312
    - pin: 2
      x: 343
      y: 312
    - pin: 3
      x: 447
      y: 312
    - pin: 4
      x: 551
      y: 312
    - pin: 5
      x: 655
      y: 312
    - pin: 6
      x: 759
      y: 312
    - pin: 7
      x: 863
      y: 312
    - pin: 8
      x: 967
      y: 312
    - pin: 9
      x: 291
      y: 412
    - pin: 10
      x: 395
      y: 412
    - pin: 11
      x: 499
      y: 412
    - pin: 12
      x: 603
      y: 412
    - pin: 13
      x: 707
      y: 412
    - pin: 14
      x: 811
      y: 412
    - pin: 15
      x: 915
      y: 412
    - pin: 16
      x: 239
      y: 512
    - pin: 17
      x: 343
      y: 512
    - pin: 18
      x: 447
      y: 512
    - pin: 19
      x: 551
      y: 512
    - pin: 20
      x: 655
      y: 512
    - pin: 21
      x: 759
      y: 512
    - pin: 22
      x: 863
      y: 512
    - pin: 23
      x: 967
      y: 512






