pins:

  - pin: A1
    function: Starter Motor Control Sense
  - pin: A5
    function: Case Ground
  - pin: A8
    function: Clutch Deactivation Top of Travel
  - pin: A9
    function: Clutch Switch Bottom of Travel
  - pin: A10
    function: High Cooling Fans
  - pin: A13
    function: Starting RC
  - pin: A14
    function: Fuel Pump Command
  - pin: A15
    function: A/C Control Relay
  - pin: A17
    function: Low Cooling Fans
  - pin: A20
    function: Main Relay Control
  - pin: A22
    function: UNUSED Shift Down
  - pin: A23
    function: UNUSED Shift Up
  - pin: A26
    function: Alternator Load Input
  - pin: A27
    function: Fuel Pump Monitor
  - pin: A29
    function: UNUSED Sensor Power
  - pin: A30
    function: UNUSED Analog Ground
  - pin: A31
    function: UNUSED Fuel Pump Monitor 2 5.2
  - pin: A32
    function: Reserve Switch
  - pin: A33
    function: Air Conditioner Pressure Sensor
  - pin: A34
    function: UNUSED Fuel Rail Pressure 5.2
  - pin: A35
    function: Pedal Position Ground 1
  - pin: A36
    function: Pedal Position Power 1
  - pin: A39
    function: UNUSED Canister Ventilation Solenoid
  - pin: A40
    function: Pedal Position Power 2
  - pin: A42
    function: Start Stop Switch
  - pin: A44
    function: UNUSED Fuel Temperature Sensor 5.2
    class: analog_inputs
  - pin: A46
    function: UNUSED Fuel Pressure Sensor
    class: analog_inputs
  - pin: A47
    function: UNUSED Ambient Air Sensor
    class: analog_inputs
  - pin: A49
    function: Fuel Pump On
  - pin: A51
    function: Generator Current Sensor
  - pin: A52
    function: Sensor Power
  - pin: A53
    function: Battery Monitor Sensor
  - pin: A54
    function: MAF Return
  - pin: A55
    function: UNUSED Diff Sensor
  - pin: A58
    function: Starter Control
  - pin: A59
    function: Pedal Position Ground 2
  - pin: A60
    function: Pedal Position Signal 2
  - pin: A61
    function: Pedal Position Signal 1
  - pin: A63
    function: UNUSED Trans Pump
  - pin: A64
    function: Ignition Power Input
  - pin: A65
    function: Fuel Pump Control
  - pin: A66
    function: UNUSED BPS
  - pin: A67
    function: UNUSED BOO
  - pin: A69
    function: UNUSED Aux Trans Pump
  - pin: A73
    function: MAF
  - pin: A75
    function: HS1 CAN High
  - pin: A76
    function: HS1 CAN Low

  - pin: A90
    function: Heated Oxygen Sensor
  - pin: A91
    function: Heated Oxygen Sensor

  - pin: A97
    function: +12 from Main Relay
  - pin: A99
    function: +12 from Main Relay

  - pin: A100
    function: Power GND
    type: GND
  - pin: A102
    function: Power GND
    type: GND
  - pin: A103
    function: Power GND
    type: GND

info:
  title: coyote
  name: A
  directory: hellen/coyote
  order: 0
  image:
    file: ford-198-a.jpg
  pins:
    - pin: A58
      x: 210
      y: 702
    - pin: A59
      x: 278
      y: 702
    - pin: A60
      x: 345
      y: 702
    - pin: A61
      x: 413
      y: 702
    - pin: A62
      x: 477
      y: 702
    - pin: A63
      x: 546
      y: 702
    - pin: A64
      x: 614
      y: 702
    - pin: A65
      x: 680
      y: 702

    - pin: A76
      x: 1346
      y: 702
#    - pin: A76
#      x: 1410
#      y: 702

    - pin: A102
      x: 1523
      y: 780
    - pin: A103
      x: 1607
      y: 780

