pins:

  - pin: A1
    function: SMC Starter Motor Control Sense (normally controlled by ACM Audio Control Module)
    type: hs

  - pin: A5
    function: Case Ground
  - pin: A8
    function: Clutch Deactivation Top of Travel
  - pin: A9
    function: Clutch Switch Bottom of Travel
  - pin: A10
    function: High Cooling Fans
  - pin: A13
    function: Alternator RC Control
  - pin: A14
    function: Fuel Pump Command
  - pin: A15
    function: A/C Control Relay
  - pin: A17
    function: Low Cooling Fans
  - pin: A20
    function: Main Relay Control
  - pin: A22
    function: TCU Shift Down (bypass to molex)
  - pin: A23
    function: TCU Shift Up (bypass to molex)
  - pin: A26
    function: Alternator Load Input
  - pin: A27
    function: Fuel Pump Monitor
  - pin: A29
    function: 5V Sensor Power
  - pin: A30
    function: Analog Ground
  - pin: A31
    function: UNUSED Fuel Pump Monitor 2 5.2
  - pin: A32
    function: Reserve Switch
  - pin: A33
    function: Air Conditioner Pressure Sensor
  - pin: A34
    function: Fuel Rail Pressure
  - pin: A35
    function: Pedal Position Ground 1
  - pin: A36
    function: Pedal Position Power 1
  - pin: A39
    function: Canister Ventilation Solenoid
  - pin: A40
    function: Pedal Position Power 2
  - pin: A42
    function: Start Stop Switch

  - pin: A44
    function: Fuel Temperature Sensor
    class: analog_inputs
    type: at

  - pin: A46
    function: Fuel Pressure Sensor
    class: analog_inputs
    type: av

  - pin: A47
    function: Ambient Air Sensor
    class: analog_inputs
    type: at

  - pin: A49
    function: UNUSED Fuel Pump On
  - pin: A51
    function: Generator Current Sensor
  - pin: A52
    function: Sensor Power
  - pin: A53
    function: Battery Monitor Sensor
  - pin: A54
    function: MAF Return
  - pin: A55
    function: UNUSED Diff Sensor

  - pin: A58
    function: SMC Starter Control
    type: ls

  - pin: A59
    function: Pedal Position Ground 2
  - pin: A60
    function: Pedal Position Signal 2
  - pin: A61
    function: Pedal Position Signal 1
  - pin: A63
    function: Differential Pump
  - pin: A64
    function: Ignition Power Input
  - pin: A65
    function: UNUSED Fuel Pump Control
  - pin: A66
    function: Brake Pedal Sensor
  - pin: A67
    function: UNUSED BOO Brake Normally Open
  - pin: A69
    function: UNUSED Aux Trans Pump
  - pin: A73
    function: MAF
  - pin: A75
    function: HS1 CAN High
  - pin: A76
    function: HS1 CAN Low

  - pin: A90
    function: Heated Oxygen Sensor
  - pin: A91
    function: Heated Oxygen Sensor

  - pin: A97
    function: +12 from Main Relay
  - pin: A99
    function: +12 from Main Relay

  - pin: A100
    function: Power GND
    type: GND
  - pin: A102
    function: Power GND
    type: GND
  - pin: A103
    function: Power GND
    type: GND

info:
  title: coyote
  name: A
  cid: a
  directory: hellen/coyote
  order: 0
  image:
    file: ford-198-a.jpg
  pins:
    # auto-generated by PinLine.java from can-log-tools
    # 1 19
    # 215 1407
    # 320
    - pin: A1
      x: 215
      y: 320
    - pin: A2
      x: 281
      y: 320
    - pin: A3
      x: 347
      y: 320
    - pin: A4
      x: 413
      y: 320
    - pin: A5
      x: 479
      y: 320
    - pin: A6
      x: 546
      y: 320
    - pin: A7
      x: 612
      y: 320
    - pin: A8
      x: 678
      y: 320
    - pin: A9
      x: 744
      y: 320
    - pin: A10
      x: 811
      y: 320

    - pin: A11
      x: 877
      y: 320
    - pin: A12
      x: 943
      y: 320
    - pin: A13
      x: 1009
      y: 320
    - pin: A14
      x: 1075
      y: 320
    - pin: A15
      x: 1142
      y: 320
    - pin: A16
      x: 1208
      y: 320
    - pin: A17
      x: 1274
      y: 320
    - pin: A18
      x: 1340
      y: 320
    - pin: A19
      x: 1407
      y: 320


    # auto-generated by PinLine.java from can-log-tools
    # 20 38
    # 215 1407
    # 380
    - pin: A20
      x: 215
      y: 380

    - pin: A21
      x: 281
      y: 380
    - pin: A22
      x: 347
      y: 380
    - pin: A23
      x: 413
      y: 380
    - pin: A24
      x: 479
      y: 380
    - pin: A25
      x: 546
      y: 380
    - pin: A26
      x: 612
      y: 380
    - pin: A27
      x: 678
      y: 380
    - pin: A28
      x: 744
      y: 380
    - pin: A29
      x: 811
      y: 380
    - pin: A30
      x: 877
      y: 380

    - pin: A31
      x: 943
      y: 380
    - pin: A32
      x: 1009
      y: 380
    - pin: A33
      x: 1075
      y: 380
    - pin: A34
      x: 1142
      y: 380
    - pin: A35
      x: 1208
      y: 380
    - pin: A36
      x: 1274
      y: 380
    - pin: A37
      x: 1340
      y: 380
    - pin: A38
      x: 1407
      y: 380

    # auto-generated by PinLine.java from can-log-tools
    # 39 57
    # 215 1407
    # 542
    - pin: A39
      x: 215
      y: 542
    - pin: A40
      x: 281
      y: 542

    - pin: A41
      x: 347
      y: 542
    - pin: A42
      x: 413
      y: 542
    - pin: A43
      x: 479
      y: 542
    - pin: A44
      x: 546
      y: 542
    - pin: A45
      x: 612
      y: 542
    - pin: A46
      x: 678
      y: 542
    - pin: A47
      x: 744
      y: 542
    - pin: A48
      x: 811
      y: 542
    - pin: A49
      x: 877
      y: 542
    - pin: A50
      x: 943
      y: 542

    - pin: A51
      x: 1009
      y: 542
    - pin: A52
      x: 1075
      y: 542
    - pin: A53
      x: 1142
      y: 542
    - pin: A54
      x: 1208
      y: 542
    - pin: A55
      x: 1274
      y: 542
    - pin: A56
      x: 1340
      y: 542
    - pin: A57
      x: 1407
      y: 542


    # auto-generated by PinLine.java from can-log-tools
    # 58 76
    # 215 1407
    # 702
    - pin: A58
      x: 215
      y: 702
    - pin: A59
      x: 281
      y: 702
    - pin: A60
      x: 347
      y: 702

    - pin: A61
      x: 413
      y: 702
    - pin: A62
      x: 479
      y: 702
    - pin: A63
      x: 546
      y: 702
    - pin: A64
      x: 612
      y: 702
    - pin: A65
      x: 678
      y: 702
    - pin: A66
      x: 744
      y: 702
    - pin: A67
      x: 811
      y: 702
    - pin: A68
      x: 877
      y: 702
    - pin: A69
      x: 943
      y: 702
    - pin: A70
      x: 1009
      y: 702

    - pin: A71
      x: 1075
      y: 702
    - pin: A72
      x: 1142
      y: 702
    - pin: A73
      x: 1208
      y: 702
    - pin: A74
      x: 1274
      y: 702
    - pin: A75
      x: 1340
      y: 702
    - pin: A76
      x: 1407
      y: 702

    # auto-generated by PinLine.java from can-log-tools
    # 77 95
    # 215 1407
    # 775
    - pin: A77
      x: 215
      y: 775
    - pin: A78
      x: 281
      y: 775
    - pin: A79
      x: 347
      y: 775
    - pin: A80
      x: 413
      y: 775

    - pin: A81
      x: 479
      y: 775
    - pin: A82
      x: 546
      y: 775
    - pin: A83
      x: 612
      y: 775
    - pin: A84
      x: 678
      y: 775
    - pin: A85
      x: 744
      y: 775
    - pin: A86
      x: 811
      y: 775
    - pin: A87
      x: 877
      y: 775
    - pin: A88
      x: 943
      y: 775
    - pin: A89
      x: 1009
      y: 775
    - pin: A90
      x: 1075
      y: 775

    - pin: A91
      x: 1142
      y: 775
    - pin: A92
      x: 1208
      y: 775
    - pin: A93
      x: 1274
      y: 775
    - pin: A94
      x: 1340
      y: 775
    - pin: A95
      x: 1407
      y: 775


    - pin: A102
      x: 1523
      y: 780
    - pin: A103
      x: 1607
      y: 780

