# copyright: Michael Holzer

pins:
  - pin: A1
    function: Power Ground
    class: gnd   
    type: gnd
    color: black

  - pin: A2
    function: 'Anti theft Switch'
    class: input_ON_OFF   
    type: [gp_low, gp_pp]
    color: brown/red 

  - pin: A3
    function: 'Power 12 Volts from injection relay'
    class: inputs
    type: ls
    # todo: '?? color yellow and "Output (low)" needs to be confirmed!''
    color: red/yellow

# gp_pp	General purpose Push-Pull	General purpose push-pull (low and high side) output,
# 600mA	Bipolar IDLE stepper (IACV)
  - pin: A4
    function: 'IACV (PinA) (IDLE stepper coil A) Note: polarity + or - ??) needs to be confirmed!'
    class: outputs
    type: gp_pp
    color: yellow

  - pin: A5
    function: 'IACV (PinD) (IDLE stepper coil A) Note: polarity + or - ??) needs to be confirmed!'
    class: outputs
    type: gp_pp
    #ts_name: IACV
    color: orange/white

  - pin: A6
    function: 'IACV (PinB) (IDLE stepper coil B) Note: polarity + or - ??) needs to be confirmed!'
    class: outputs
    type: gp_pp
    #ts_name: IACV
    color: brown/rosa

  - pin: A7
    function: 'IACV (PinC) (IDLE stepper coil B) Note: polarity + or - ??) needs to be confirmed!'
    class: outputs
    type: gp_pp
    #ts_name: IACV
    color: rosa/white

  - pin: A8
    function: Ignition Coil 1
    class: outputs
    type: ign
    color: yellow/black

  - pin: B1
    function: Injector 1
    class: outputs
    type: inj
    # note color: English manual is unclear on second color! 
    # "VE" appears to be original italian term "verde" for english "green"
    color: gray/green

  - pin: B2
    function: 'Sensors common ground (IAT, ECT, Map change Switch)'
    class: sgnd
    type: sgnd
    color: violet/black

  - pin: B3
    function: 'Throttle position sensor (TPS) Sensor ground / Lambda O2 Sensor ground'
    class: sgnd
    type: sgnd
    color: violet/black

  - pin: B4
    function: 'Crank Sensor - Phonic Wheel Shield'
    class: ??
    type: VR
    color: black

  - pin: B5
    function: 'Throttle position sensor (TPS) +5  Volts (link between C5-C6-B5)'
    class: analog_inputs
    type: TPS
    color: blue

  - pin: B6
    # not used
    function: not used

  - pin: B7
    function: 'Throttle position sensor (TPS) Sensor signal output'
    class: analog_inputs
    type: TPS
    color: yellow/blue

  - pin: B8
    function: Ignition Coil 2
    class: outputs
    color: yellow/black
    type: ign

  - pin: C1
    function: Injector 2
    class: outputs
    type: inj
    color: gray

  - pin: C2
    function: 'RPM/Tachometer Output to dashboard'
    class: ??
    type: ??
    color: gray/red


  - pin: C3
    function: 'Crank Sensor - Phonic Wheel (VR) NOTE!! ToDo: correct  + and - side assignment required!!'
    class: event_inputs
    type: vr
    color: white or black

  - pin: C4
    function: 'Crank Sensor - Phonic Wheel (VR) NOTE!! ToDo: correct  + and - side assignment required!!'
    class: event_inputs
    type: vr
    color: white or black

  - pin: C5
    function: 'Intake Air Temp (IAT) Sensor +5 Volts (link between C5-C6-B5)'
    class: analog_inputs
    type: 5V
    color: green

  - pin: C6
    function: 'Engine Coolant Temp  (ECT) Sensor +5 Volts (link between C5-C6-B5)'
    class: analog_inputs
    type: 5V
    color: white/violet

  - pin: C7
    function: 'Lambda sensor'

  - pin: C8
    function: Power Ground
    class: pgnd
    type: pgnd
    color: black

  - pin: D1
    function: Ignition Coil 3
    class: outputs
    type: ign
    color: blue/black

  - pin: D2
    class: outputs
    function: 'fuel pump relay exit (grounding through ecu)'
    type: gnd
    color: blue/green

  - pin: D3
    function: 'Injection Relay exit (grounding through ecu)'
    class: gnd
    type: ??
    color: violet/brown

  - pin: D4
    function: 'Cooling fan relay exit (grounding through ecu)'
    class: gnd
    type: ??
    color: orange/black

  - pin: D5
    # not used
    function: not used

  - pin: D6
    class: outputs
    function: 'Water temp output to dashboard'
    type: at
    color: brown/violet

  - pin: D7
    # not required by rusEFI??
    function: 'OBD2 - DIAG GROUND)'
    class: OBD2
    type: gnd

  - pin: D8
    function: Power Ground
    class: pgnd
    type: pgnd
    color: black

  - pin: E1
    # not used
    function: not used

  - pin: E2
    # not required by rusEFI??
    function: 'OBD2 - DIAG RS232 Tx/Rx'
    class: OBD2

  - pin: E3
    # not required by rusEFI?? (enable ECU programming?)
    function: 'enable ECU programming when grounded'

  - pin: E4
    function: 'Neutral switch'
    class: input_ON_OFF

  - pin: E5
    function: 'MAP CHANGE switch'
    class: input_ON_OFF

  - pin: E6
    function: 'Lambda O2 Sensor'

  - pin: E7
    function: 'LIGHTS Hi/Low Beam Relay exit (grounding through ecu)'
    class: outputs
    type: ??
    color: yellow/green

  - pin: E8
    function: Injector 3
    class: outputs
    type: inj
    color: blue/gray

  - pin: F1
    function: Power Ground
    class: pgnd
    type: pgnd
    color: black

  - pin: F2
    # not required by rusEFI??
    function: 'OBD2 - DIAG RS232 Tx/Rx'
    class: OBD2

  - pin: F3
    # not required by rusEFI?? (OBD2?)
    function: 'OBD2 - K-line'
    class: OBD2

  - pin: F4
    # not required by rusEFI?? (OBD2?)
    function: 'OBD2- L-Line'
    class: OBD2

  - pin: F5
    function: 'Tilt Sensor (Grounded or Open circuit)'
    class: input_ON_OFF

  - pin: F6
    function: 'side stand Sensor Input  (grounded or open circuit)'
    class: input_ON_OFF
    color: white

  - pin: F7
    function: 'Injection warning light (MIL)'
    class: analog_outputs
    type: MIL
    color: red/black

  - pin: F8
    function: 'Solenoid Exhaust & Airbox Flaps  (grounding through ecu)'
    class: analog_inputs
    type: ??
    color: green

info:
  cid: B3W
  title: Benelli_Walbro
  directory: Benelli_Walbro
  name: 'Benelli_Walbro  !! NOTE: status is DRAFT, last change by Papysoupape !! - there are potential wrong pin assignments'
  board_url: https://rusefi.com/s/Benelli_Walbro
  image:
    file: Benelli_Walbro.jpg
  pins:
    - pin: A1
      x: 580
      y: 150

    - pin: A2
      x: 512
      y: 150

    - pin: A3
      x: 466
      y: 150

    - pin: A4
      x: 409
      y: 150

    - pin: A5
      x: 362
      y: 150

    - pin: A6
      x: 313
      y: 150

    - pin: A7
      x: 258
      y: 150

    - pin: A8
      x: 197
      y: 150

    - pin: B1
      x: 580
      y: 226

    - pin: B2
      x: 512
      y: 226

    - pin: B3
      x: 466
      y: 226

    - pin: B4
      x: 409
      y: 226

    - pin: B5
      x: 362
      y: 226

    - pin: B6
      x: 313
      y: 226

    - pin: B7
      x: 258
      y: 226

    - pin: B8
      x: 197
      y: 226

    - pin: C1
      x: 580
      y: 305

    - pin: C2
      x: 512
      y: 305

    - pin: C3
      x: 466
      y: 305

    - pin: C4
      x: 409
      y: 305

    - pin: C5
      x: 362
      y: 305

    - pin: C6
      x: 313
      y: 305

    - pin: C7
      x: 258
      y: 305

    - pin: C8
      x: 197
      y: 305

    - pin: D1
      x: 1384
      y: 150

    - pin: D2
      x: 1320
      y: 150

    - pin: D3
      x: 1264
      y: 150

    - pin: D4
      x: 1209
      y: 150

    - pin: D5
      x: 1160
      y: 150

    - pin: D6
      x: 1114
      y: 150

    - pin: D7
      x: 1062
      y: 150

    - pin: D8
      x: 998
      y: 150

    - pin: E1
      x: 1384
      y: 226

    - pin: E2
      x: 1320
      y: 226

    - pin: E3
      x: 1264
      y: 226

    - pin: E4
      x: 1209
      y: 226

    - pin: E5
      x: 1160
      y: 226

    - pin: E6
      x: 1114
      y: 226

    - pin: E7
      x: 1062
      y: 226

    - pin: E8
      x: 998
      y: 226

    - pin: F1
      x: 1384
      y: 305

    - pin: F2
      x: 1320
      y: 305

    - pin: F3
      x: 1264
      y: 305

    - pin: F4
      x: 1209
      y: 305

    - pin: F5
      x: 1160
      y: 305

    - pin: F6
      x: 1114
      y: 305

    - pin: F7
      x: 1061
      y: 305

    - pin: F8
      x: 998
      y: 305
