meta: config/boards/hellen_meta.h

pins:
  - pin: 1B
    function: Injector 4 Output
    class: outputs
    type: ls
    id: TLE9104_0_OUT_3
    ts_name: ___ - Injector 4
    color: orange

  - pin: 2B
    function: Injector 3 Output
    class: outputs
    type: ls
    id: TLE9104_0_OUT_2
    ts_name: ___ - Injector 3
    color: blue

  - pin: 3B
    function: Injector 2 Output
    class: outputs
    type: ls
    id: TLE9104_0_OUT_1
    ts_name: ___ - Injector 2
    color: white

  - pin: 4B
    function: Injector 1 Output
    class: outputs
    type: ls
    id: TLE9104_0_OUT_0
    ts_name: ___ - Injector 1
    color: green

  - pin: 5B
    function: Fuel Pump Relay
    color: grey
    class: outputs
    type: ls
    id: TLE9104_2_OUT_1
    ts_name: ___ Fuel Pump Relay
    color: white

  - pin: 6B
    color: orange
    function: Idle Output
    class: outputs
    type: ls
    id: TLE9104_2_OUT_0
    ts_name: ___ Idle Output
    color: yellow

  - pin: 7B
    function: CAN High
    color: green
    type: can

  - pin: 8B
    function: CAN Low
    color: blue
    type: can

  - pin: 9B
    function: +12v Bat+
    color: red
    type: 12V

  - pin: 10B
    meta: H144_IGN_4
    class: outputs
    ts_name: ___ Coil 4
    color: orange

  - pin: 11B
    meta: H144_IGN_3
    class: outputs
    ts_name: ___ Coil 3
    color: blue

  - pin: 12B
    meta: H144_IGN_2
    class: outputs
    ts_name: ___ Coil 2
    color: white

  - pin: 13B
    meta: H144_IGN_1
    class: outputs
    ts_name: ___ Coil 1
    color: green

  - pin: 14B
    function: Tachometer Output
    class: outputs
    color: yellow
    type: ls
    id: TLE9104_2_OUT_4
    ts_name: ___ - Tachometer Output

  - pin: NONE
    function: Extra Output P1
    class: outputs
    color: yellow
    type: ls
    id: TLE9104_2_OUT_3
    ts_name: ___ - Extra Out

  - pin: 15B
    meta: H144_IN_SENS1
    class: switch_inputs
    function: Digital Input 1
    ts_name: ___ - Digital In 1
    color: green

  - pin: 16B
    id: [H144_IN_MAP1_DIGITAL, H144_IN_MAP1_DIGITAL, H144_IN_MAP1]
    class: [event_inputs, switch_inputs, analog_inputs]
    type: hall
    ts_name: ___ - Digital/analog input 2
    function: Digital/event/analog input (cannot be used simultaneously with VR1)

  - pin: 17B
    id: [H144_IN_SENS4, H144_IN_SENS4]
    class: [event_inputs, switch_inputs]
    type: hall
    ts_name: ___ - Digital input 1
    function: Digital/event input (cannot be used simultaneously with VR1)

  - pin: 17B16B
    meta: H144_IN_CRANK
    class: event_inputs
    function: VR1 (cannot be used simultaneously with Hall1 and Hall2)
    type: vr
    ts_name: 17A/17B VR Input 1 (Discrete)

  - pin: 18B
    meta: H144_IN_TPS
    class: analog_inputs
    function: TPS1 Sensor Input
    ts_name: ___ - TPS1
    type: av
    color: orange

  - pin: 19B
    meta: H144_IN_CLT
    class: analog_inputs
    function: CLT Sensor Input
    ts_name: ___ - CLT
    type: av
    color: grey


  - pin: 20B
    meta: H144_IN_IAT
    class: analog_inputs
    type: av
    function: IAT Sensor Input
    ts_name: ___ - IAT
    color: blue

  - pin: 21B
    meta: H144_IN_O2S2
    class: analog_inputs
    ts_name: ___ MAP
    function: MAP input
    type: av
    color: yellow

  - pin: 22B
    meta: H144_IN_TPS2
    class: analog_inputs
    ts_name: ___ TPS2
    function: TPS2 sensor input
    type: av
    color: blue

  - pin: 23B
    function: Sensor +5v Power Feed
    type: 5v
    color: orange

  - pin: 24B
    id: [H144_IN_D_4, H144_IN_D_4]
    class: [event_inputs, switch_inputs]
    type: hall
    ts_name: ___ - Digital Input 6
    function: Digital Input 6 (cannot be used simultaneously with VR3)

  - pin: 25B
    id: [H144_IN_AUX3_DIGITAL, H144_IN_AUX3_DIGITAL, H144_IN_AUX3_ANALOG]
    class: [event_inputs, switch_inputs, analog_inputs]
    type: hall
    ts_name: ___ - Digital/analog Input 5
    function: Digital/analog Input 5 (cannot be used simultaneously with VR3)

  - pin: 24B25B
    meta: H144_IN_VSS
    class: event_inputs
    function: VR3 (cannot be used simultaneously with Hall5 and Hall6)
    type: vr
    ts_name: 24A/25A VR Input 3 (MAX9924)

  - pin: 26B
    function: GND
    type: GND

  - pin: 27B
    function: GNDA
    type: gnd
    color: black

  - pin: 28B
    meta: H144_IN_AUX1_ANALOG
    class: analog_inputs
    ts_name: ___ AUX1
    function: AUX input 1
    type: av

  - pin: 29B
    function: WBO1 Heater Negative (pin 3)
    color: white
    type: wbo

  - pin: 30B
    function: WBO1 Vs/Ip (Vm) (pin 2)
    type: wbo
    color: yellow

  - pin: 31B
    function: WBO1 Ip (pin 1)
    type: wbo
    color: red

  - pin: 32B
    function: WBO1 CalR (pin 5)
    type: wbo
    color: green

  - pin: 33B
    function: WBO1 Vs (Un) (pin 6)
    type: wbo
    color: black

  - pin: 34B
    function: WBO1 Heater Positive (pin 4)
    type: wbo
    color: grey

info:
  cid: 34-4
  order: 1
  title: AlphaX Gold
  directory: hellen/alphax-gold
  name: AlphaX Gold
  image:
    file: 34pins-4k.jpg
  pins:
    - pin: 1B
      x: 75
      y: 90
    - pin: 2B
      x: 95
      y: 90
    - pin: 3B
      x: 120
      y: 90
    - pin: 4B
      x: 145
      y: 90
    - pin: 5B
      x: 165
      y: 90
    - pin: 6B
      x: 190
      y: 90
    - pin: 7B
      x: 215
      y: 90
    - pin: 8B
      x: 240
      y: 90
    - pin: 9B
      x: 265
      y: 90
    - pin: 10B
      x: 85
      y: 120
    - pin: 11B
      x: 105
      y: 120
    - pin: 12B
      x: 130
      y: 120
    - pin: 13B
      x: 155
      y: 120
    - pin: 14B
      x: 180
      y: 120
    - pin: 15B
      x: 205
      y: 120
    - pin: 16B
      x: 225
      y: 120
    - pin: 17B
      x: 245
      y: 120
    - pin: 18B
      x: 85
      y: 150
    - pin: 19B
      x: 110
      y: 150
    - pin: 20B
      x: 130
      y: 150
    - pin: 21B
      x: 155
      y: 150
    - pin: 22B
      x: 180
      y: 150
    - pin: 23B
      x: 205
      y: 150
    - pin: 24B
      x: 225
      y: 150
    - pin: 25B
      x: 245
      y: 150
    - pin: 26B
      x: 74
      y: 180
    - pin: 27B
      x: 98
      y: 180
    - pin: 28B
      x: 122
      y: 180
    - pin: 29B
      x: 146
      y: 180
    - pin: 30B
      x: 170
      y: 180
    - pin: 31B
      x: 195
      y: 180
    - pin: 32B
      x: 220
      y: 180
    - pin: 33B
      x: 245
      y: 180
    - pin: 34B
      x: 265
      y: 180
