#
# microRusEfi board
# https://github.com/rusefi/rusefi/wiki/Hardware_microRusEfi_wiring
#

outputs:
  # TLE8888 injector channels
  TLE8888_PIN_1: "37 - Injector 1"
  TLE8888_PIN_2: "38 - Injector 2"
  TLE8888_PIN_3: "41 - Injector 3"
  TLE8888_PIN_4: "42 - Injector 4"
  # TC4427 ignition outputs (5v)
  GPIOD_4: "9 - Ignition 1"
  GPIOD_3: "10 - Ignition 2"
  GPIOD_2: "11 - Ignition 3"
  GPIOD_1: "12 - Ignition 4"
  # TC4427 general purpose output (selectable 5v/12v)
  GPIOD_7: "14 - GP Out 5"
  GPIOD_6: "13 - GP Out 6"

  # default VVT TLE8888 high current low side: VVT1 TLE8888_OUT6
  TLE8888_PIN_6: "7 - Lowside 1"
  # default Idle Air Control TLE8888 high current low side: VVT2 TLE8888_OUT5
  TLE8888_PIN_5: "3 - Lowside 2"

  # TLE8888 half bridges (pushpull, lowside, or high-low) TLE8888_OUT21#91
  TLE8888_PIN_21: "35 - GP Out 1"
  # TLE8888 half bridges (pushpull, lowside, or high-low) TLE8888_OUT22#89
  TLE8888_PIN_22: "34 - GP Out 2"
  # TLE8888 half bridges (pushpull, lowside, or high-low) TLE8888_OUT23
  TLE8888_PIN_23: "33 - GP Out 3"
  # TLE8888 half bridges (pushpull, lowside, or high-low) TLE8888_OUT24
  TLE8888_PIN_24: "43 - GP Out 4"

  # J2
  GPIOA_15: "AUX J2 PA15"
  GPIOB_8:  "AUX J2 PB8"
  GPIOB_9:  "AUX J2 PB9"
  GPIOC_12: "AUX J2 PC12"
  GPIOB_0: "AUX AV8 reuse"
  GPIOB_1: "AUX AV9 reuse"
  GPIOA_4: "AUX AV10 reuse"
  GPIOC_4: "AUX AV6 reuse"


  # Dual purpose input/output
#  TLE8888_PIN_12:  "AV6 outmode"
#  TLE8888_PIN_11:  "AV8 outmode"
#  TLE8888_PIN_10:  "AV9 outmode"
#  TLE8888_PIN_13: "AV10 outmode"




event_inputs:
  # RC filter input for hall
  GPIOA_5: "25 - Hall Cam"
  # TLE8888 VR/hall conditioner
  GPIOC_6: "45 - VR/Hall Crank"

switch_inputs:
  GPIOE_10: "Brake Switch"
  GPIOG_1: "Clutch Switch"

analog_inputs:
  # PA0 CLT
  EFI_ADC_0: "18 - AN temp 1"
  
  # PA1 IAT
  EFI_ADC_1: "23 - AN temp 2"
  
  # PA2
  EFI_ADC_2: "24 - AN temp 3"
  # PA3
  EFI_ADC_3: "22 - AN temp 4"
  # PA4 - also AUX REUSE
  EFI_ADC_4: "28 - AN volt 10"
  
  # PA6 pull-down R31
  EFI_ADC_6: "26 - AN volt 2"
  
  # PA7 - usually PPS Pedal Position Sensor
  EFI_ADC_7: "31 - AN volt 3"
  # PB0 - also AUX REUSE
  EFI_ADC_8: "36 - AN volt 8"
  # PB1 - also AUX REUSE
  EFI_ADC_9: "40 - AN volt 9"
  
  # PC0 MAP
  EFI_ADC_10: "27 - AN volt 1"
  # PC1
  EFI_ADC_11: "Battery Sense"
  # PC2 pull-down R131
  EFI_ADC_12: "19 - AN volt 4"
  
  # PC3 TPS pull-down R41
  EFI_ADC_13: "20 - AN volt 5"
  
  # PC4 - also AUX REUSE
  EFI_ADC_14: "32 - AN volt 6"
  # PC5
  EFI_ADC_15: "30 - AN volt 7"
