# https://github.com/rusefi/rusefi/blob/master/firmware/config/boards/hellen/hellen_meta.h

pins:
  - pin: A1
    function: Power Ground
    type: gnd
    color: black

  - pin: A2
    id: EFI_ADC_5
    class: analog_inputs
    function: +12V
    ts_name: A2 Battery Sense
    type: 12v
    color: red

  - pin: A3
    # H144_OUT_IO12
    id: GPIOA_8
    class: outputs
    function: Fuel Pump Relay Output (low)
    type: ls
    ts_name: A3 - Fuel Pump
    color: purple

  - pin: A4
    # H144_OUT_IO13
    id: GPIOG_6
    class: outputs
    function: Tachometer Output
    ts_name: A4 - Tachometer
    color: purple

  - pin: A5
    function: Sensor Ground
    type: gnd
    color: brown

  - pin: A6
    # H144_IGN_1
    id: GPIOC_13
    class: outputs
    function: Smart Ignition 1
    type: ign
    ts_name: A6 - Ignition 1
    color: yellow

  - pin: A7
    # H144_IGN_2
    id: GPIOE_5
    class: outputs
    function: Smart Ignition 2 Output
    type: ign
    ts_name: A7 - Ignition 2
    color: yellow

  - pin: A8
    # H144_LS_1
    id: GPIOG_7
    function: Injector 1 Output
    class: outputs
    type: inj
    ts_name: A8 - Injector 1
    color: blue

  - pin: B1
    function: Power Ground
    type: gnd
    color: black

  - pin: On-board MAP
    # H144_IN_MAP3
    id: EFI_ADC_2
    class: analog_inputs
    function: MAP Sensor Input
    ts_name: On-board MAP
    color: orange

  - pin: B2
    # H144_IN_MAP2 AIN10 PC1
    id: EFI_ADC_11
    class: analog_inputs
    function: MAP Sensor Input
    ts_name: B2 - MAP
    color: orange

  - pin: B3
    # H144_IN_IAT AIN14 PC3
    id: EFI_ADC_13
    class: analog_inputs
    function: IAT Sensor Input
    ts_name: B3 - IAT
    color: orange

  - pin: B4
    # H144_IN_O2S2 AIN12 PA1
    id: EFI_ADC_1
    class: analog_inputs
    function: O2 Sensor Input
    ts_name: B4 - O2
    color: orange

  - pin: B5
    # H144_IN_TPS AIN17 PA4
    id: EFI_ADC_4
    class: analog_inputs
    function: TPS Sensor Input
    ts_name: B5 - TPS
    color: orange

  - pin: B6
    function: Sensor +5v Power Feed
    type: 5v
    color: orange

  - pin: B7
    # H144_IN_CLT AIN11 PC2
    id: EFI_ADC_12
    class: analog_inputs
    function: CLT Sensor Input
    ts_name: B7 - CLT
    color: orange

  - pin: B8
    # H144_LS_2
    id: GPIOG_8
    function: Injector 2 Output
    class: outputs
    type: inj
    ts_name: B8 - Injector 2
    color: blue

  - pin: C1
    # H144_OUT_PWM4
    id: GPIOC_8
    class: outputs
    function: Fan Relay or 5A Power Output (low)
    type: ls
    ts_name: C1 - Fan Relay
    color: purple

  - pin: C2
    # H144_IN_D_3
    id: [GPIOE_14, GPIOE_14]
    class: [event_inputs, switch_inputs]
    function: Crank Sensor -
    type: hall
    ts_name: C2 - Crank- (hall)
    color: white

  - pin: C3
    # H144_IN_D_1
    id: [GPIOE_12, GPIOE_12]
    class: [event_inputs, switch_inputs]
    function: Crank Sensor +
    type: hall
    ts_name: C3 - Crank+ (hall)
    color: gray

  - pin: C2C3
    # H144_IN_CRANK
    id: GPIOB_1
    class: event_inputs
    function: Crank Sensor (VR)
    type: hall
    ts_name: C2/C3 Crank Sensor VR
    color: gray

  - pin: C4
    # H144_IN_VSS
    id: GPIOF_11
    class: switch_inputs
    function: 2Step Digital Input
    type: hall
    ts_name: C4 - 2Step/Digital
    color: gray

  - pin: C5
    function: CAN bus high (CANH)
    type: can
    color: green

  - pin: C6
    function: CAN bus low (CANL)
    type: can
    color: blue

  - pin: C7
    # H144_IN_CAM
    id: [GPIOA_6, GPIOA_6, EFI_ADC_6]
    class: [event_inputs, switch_inputs, analog_inputs]
    function: Camshaft HALL Sensor or Generic Digital Input
    type: hall
    ts_name: C7 - CAM Hall/Digital
    color: brown

  - pin: C8
    # H144_OUT_PWM1
    id: GPIOD_13
    class: outputs
    function: Idle Output (low)
    type: ls
    ts_name: C8 - Idle
    color: purple

  - pin: D1
    # H144_LS_3
    id: GPIOD_11
    function: Injector 3
    class: outputs
    type: inj
    ts_name: D1 - Injector 3
    color: blue

  - pin: D2
    # H144_OUT_PWM3
    id: GPIOC_7
    function: Out Boost
    class: outputs
    ts_name: D2 - Out Boost
    color: blue

  - pin: D4
    # H144_IN_AUX1
    id: EFI_ADC_8
    class: analog_inputs
    function: TPS2 Sensor Input
    ts_name: D4 - TPS2
    color: orange

  - pin: D5
    # IN_PPS
    id: EFI_ADC_3
    class: analog_inputs
    function: PPS Sensor Input
    ts_name: D5 - PPS
    color: orange

  - pin: D6
    # H144_IGN_3
    id: GPIOE_4
    class: outputs
    function: Smart Ignition 3 Output
    type: ign
    ts_name: D6 - Ignition 3
    color: yellow

  - pin: D7
    # H144_IGN_4
    id: GPIOE_3
    class: outputs
    function: Smart Ignition 4 Output
    type: ign
    ts_name: D7 - Ignition 4
    color: yellow

  - pin: D8
    function: Power Ground
    type: gnd
    color: black

  - pin: E1
    # H144_LS_4
    id: GPIOD_10
    function: Injector 4
    class: outputs
    type: inj
    ts_name: E1 - Injector 4
    color: blue

  - pin: E2
    # H144_OUT_IO6
    id: GPIOG_11
    function: Out NOS
    class: outputs
    ts_name: E2 - Out NOS
    color: blue

  - pin: E8
    function: ETB negative
    type: etb

  - pin: F1
    # H144_OUT_PWM5
    id: GPIOC_9
    class: outputs
    function: Idle2 Output (low)
    type: ls
    ts_name: F1 - Idle2
    color: purple

  - pin: F2
    # H144_OUT_PWM7
    id: GPIOD_15
    function: VVT#1
    class: outputs
    type: inj
    ts_name: F2 - VVT#1

  - pin: F4
    # H144_OUT_PWM8
    id: GPIOD_12
    function: VVT#2
    class: outputs
    type: inj
    ts_name: F4 - VVT#2

  - pin: F5
    # H144_OUT_IO10
    id: GPIOG_12
    class: outputs
    ts_name: F5 - MAIN
    function: Main relay control
    type: ls
    color: white

  - pin: F6
    # H144_IN_AUX2
    id: EFI_ADC_14
    class: analog_inputs
    function: PPS2 Sensor Input
    ts_name: F6 - PPS2
    color: orange

  - pin: F8
    function: ETB positive
    type: etb

info:
  title: AlphaX 4chan
  name: AlphaX 4chan
  board_url: https://rusefi.com/s/4chan
  image:
    file: alphax-4chan.jpg
  pins:
    - pin: A1
      x: 580
      y: 150

    - pin: A2
      x: 512
      y: 150

    - pin: A3
      x: 466
      y: 150

    - pin: A4
      x: 409
      y: 150

    - pin: A5
      x: 362
      y: 150

    - pin: A6
      x: 313
      y: 150

    - pin: A7
      x: 258
      y: 150

    - pin: A8
      x: 197
      y: 150

    - pin: B1
      x: 580
      y: 226

    - pin: B2
      x: 512
      y: 226

    - pin: B3
      x: 466
      y: 226

    - pin: B4
      x: 409
      y: 226

    - pin: B5
      x: 362
      y: 226

    - pin: B6
      x: 313
      y: 226

    - pin: B7
      x: 258
      y: 226

    - pin: B8
      x: 197
      y: 226

    - pin: C1
      x: 580
      y: 305

    - pin: C2
      x: 512
      y: 305

    - pin: C3
      x: 466
      y: 305

    - pin: C4
      x: 409
      y: 305

    - pin: C5
      x: 362
      y: 305

    - pin: C6
      x: 313
      y: 305

    - pin: C7
      x: 258
      y: 305

    - pin: C8
      x: 197
      y: 305

    - pin: D1
      x: 1384
      y: 150

    - pin: D2
      x: 1320
      y: 150

    - pin: D3
      x: 1264
      y: 150

    - pin: D4
      x: 1209
      y: 150

    - pin: D5
      x: 1160
      y: 150

    - pin: D6
      x: 1114
      y: 150

    - pin: D7
      x: 1114
      y: 150

    - pin: D8
      x: 998
      y: 150

    - pin: E1
      x: 1384
      y: 226

    - pin: E2
      x: 1320
      y: 226

    - pin: E3
      x: 1264
      y: 226

    - pin: E4
      x: 1209
      y: 226

    - pin: E5
      x: 1160
      y: 226

    - pin: E6
      x: 1114
      y: 226

    - pin: E7
      x: 1114
      y: 305

    - pin: E8
      x: 998
      y: 226

    - pin: F1
      x: 1384
      y: 305

    - pin: F2
      x: 1320
      y: 305

    - pin: F3
      x: 1264
      y: 305

    - pin: F4
      x: 1209
      y: 305

    - pin: F5
      x: 1160
      y: 305

    - pin: F6
      x: 1114
      y: 305

    - pin: F7
      x: 1061
      y: 305

    - pin: F8
      x: 998
      y: 305
