#
# microRusEfi board
# https://github.com/rusefi/rusefi/wiki/Hardware_microRusEfi_wiring
#

pins:
  - pin: 1
    id: EFI_ADC_11
    class: analog_inputs
    color: white right
    function: 12V Supply from main relay output, see also pin 29. DO NOT FORGET ABOUT PIN 5.
    ts_name: Battery Sense
    type: 12V

  - pin: 2
    function: Power GND
    type: pgnd
    color: white

  # default Idle Air Control TLE8888 high current low side: VVT2 TLE8888_OUT5
  - pin: 3
    id: TLE8888_PIN_5
    class: outputs
    color: white
    function: Idle solenoid
    ts_name: 3 - Lowside 2
    type: ls

  - pin: 4
    function: ETB+
    type: etb
    color: white

  - pin: 5
    function: 12V supply from Key (turn on/off power) primary source of +12v
    type: 12V
    color: black

  - pin: 6
    function: Power GND
    type: pgnd
    color: black

  # default VVT TLE8888 high current low side: VVT1 TLE8888_OUT6
  - pin: 7
    id: TLE8888_PIN_6
    class: outputs
    color: black
    function: VVT
    ts_name: 7 - Lowside 1
    type: ls

  - pin: 8
    function: ETB-
    type: etb
    color: black

  # TC4427 ignition outputs (5v)
  - pin: 9
    id: D4
    class: outputs
    color: dark blue
    function: Ignition 1
    ts_name: 9 - Ignition 1
    type: ign

  - pin: 10
    id: D3
    class: outputs
    color: dark blue
    function: Ignition 2
    ts_name: 10 - Ignition 2
    type: ign

  - pin: 11
    id: D2
    class: outputs
    color: dark blue
    function: Ignition 3
    ts_name: 11 - Ignition 3
    type: ign

  - pin: 12
    id: D1
    class: outputs
    color: dark blue
    function: Ignition 4
    ts_name: 12 - Ignition 4
    type: ign

  - pin: 13
    id: D6
    class: outputs
    color: yellow
    function: Alternator (see JP2 jumper note)
    ts_name: 13 - GP Out 6
    type: gp_high

  # TC4427 general purpose output (selectable 5v/12v)
  - pin: 14
    id: D7
    class: outputs
    color: yellow
    function: (see JP2 jumper note)
    ts_name: 14 - GP Out 5
    type: gp_high

  - pin: 15
    function: USB white wire https://youtu.be/4v2VnP-YdlQ
    type: usb
    color: yellow

  - pin: 16
    function: USB green wire https://youtu.be/4v2VnP-YdlQ
    type: usb
    color: yellow

  - pin: 17
    function: Signal GND
    type: sgnd
    color: red right

  - pin: 18
    id: [A0, EFI_ADC_0]
    class: [switch_inputs, analog_inputs]
    color: red
    function: CLT sensor
    ts_name: 18 - AN temp 1
    type: at

  - pin: 19
    id: [C2, EFI_ADC_12]
    class: [switch_inputs, analog_inputs]
    color: red
    function: Starting from version 0.5.0 this pin can be used as 5V input for USB connection through main connector (No need to open case to access micro-USB connector) WATCH OUT FOR D7
    ts_name: 19 - AN volt 4
    type: av
  
  - pin: 20
    id: [C3, EFI_ADC_13]
    class: [switch_inputs, analog_inputs]
    color: red left
    function: Throttle position sensor (TPS)
    ts_name: 20 - AN volt 5
    type: av

  - pin: 21
    function: Signal GND
    type: sgnd
    color: dark green

  - pin: 22
    id: [A3, A3, EFI_ADC_3]
    class: [event_inputs, switch_inputs, analog_inputs]
    color: dark green
    ts_name: 22 - AN temp 4 or Hall Input
    type: at

  - pin: 23
    id: [A1, A1, EFI_ADC_1, A1]
    class: [event_inputs, switch_inputs, analog_inputs, sent_inputs]
    color: dark green
    function: IAT sensor or SENT input!
    ts_name: 23 - AN temp 2
    type: at

  - pin: 24
    id: [A2, A2, EFI_ADC_2]
    class: [event_inputs, switch_inputs, analog_inputs]
    color: dark green
    ts_name: 24 - AN temp 3 or Hall Input
    type: at

  # RC filter input for hall
  - pin: 25
    id: [A5, A5]
    class: [event_inputs, switch_inputs]
    color: light blue right
    ts_name: 25 - Hall Cam
    type: hall
    
  - pin: 26
    id: [A6, EFI_ADC_6]
    class: [switch_inputs, analog_inputs]
    color: light blue
    function: TPS2
    ts_name: 26 - AN volt 2
    type: av

  - pin: 27
    id: [C0, EFI_ADC_10]
    class: [switch_inputs, analog_inputs]
    color: light blue
    function: MAP sensor
    ts_name: 27 - AN volt 1
    type: av

  - pin: 28
    id: [A4, A4, EFI_ADC_4]
    class: [outputs, switch_inputs, analog_inputs]
    color: light blue left
    function: AN volt 10, for aux see R85
    ts_name: 28 - AN volt 10, Aux Reuse
    type: av

  - id: E0
    class: outputs
    ts_name: AUX J6

  - id: B11
    class: outputs
    ts_name: AUX J12

  - id: B10
    class: outputs
    ts_name: AUX J13

  - pin: 29
    function: Main relay control signal (low side)
    type: mr
    color: pink right

  - pin: 30
    id: [C5, EFI_ADC_15]
    class: [switch_inputs, analog_inputs]
    color: pink
    function: Throttle Pedal Position Sensor 2 (PPS2)
    ts_name: 30 - AN volt 7
    type: av

  - pin: 31
    id: [A7, EFI_ADC_7]
    class: [switch_inputs, analog_inputs]
    color: pink
    function: Throttle Pedal Position Sensor (PPS)
    ts_name: 31 - AN volt 3
    type: av

  - pin: 32
    id: [C4, C4, EFI_ADC_14]
    class: [outputs, switch_inputs, analog_inputs]
    color: pink
    function: External wideband O2 sensor WBO AFR EGO, for aux see R86
    ts_name: 32 - AN volt 6, Aux Reuse
    type: av

  # TLE8888 half bridges (pushpull, lowside, or high-low) TLE8888_OUT23
  - pin: 33
    id: TLE8888_PIN_23
    class: outputs
    color: orange right
    function: (IDLE stepper coil 2+)
    ts_name: 33 - GP Out 3
    type: [gp_low, gp_pp]

  # TLE8888 half bridges (pushpull, lowside, or high-low) TLE8888_OUT22#89
  - pin: 34
    id: TLE8888_PIN_22
    class: outputs
    color: orange
    function: Fan relay (IDLE stepper coil 1-)
    ts_name: 34 - GP Out 2
    type: [gp_low, gp_pp]

  # TLE8888 half bridges (pushpull, lowside, or high-low) TLE8888_OUT21#91
  - pin: 35
    id: TLE8888_PIN_21
    class: outputs   
    color: orange 
    function: Fuel pump relay (IDLE stepper coil 1+)
    ts_name: 35 - GP Out 1
    type: [gp_low, gp_pp]

  - pin: 36
    id: [B0, B0, EFI_ADC_8]
    class: [outputs, switch_inputs, analog_inputs]
    color: orange left
    function: AN volt 8, for aux see R84
    ts_name: 36 - AN volt 8, Aux Reuse
    type: av

  - pin: 37
    id: TLE8888_PIN_1
    class: outputs
    color: grey right
    function: Injector 1
    ts_name: 37 - Injector 1
    type: inj

  - pin: 38
    id: TLE8888_PIN_2
    class: outputs
    color: grey
    function: Injector 2
    ts_name: 38 - Injector 2
    type: inj

  - pin: 39
    function: MAP sensor supply
    type: 5v
    color: grey

  - pin: 40
    id: [B1, B1, EFI_ADC_9]
    class: [outputs, switch_inputs, analog_inputs]
    color: grey
    function: AN volt 9 without R30, low side output with R30
    ts_name: 40 - AN volt 9, Aux Reuse
    type: av

  - pin: 41
    id: TLE8888_PIN_3
    class: outputs
    color: brown right
    function: Injector 3
    ts_name: 41 - Injector 3
    type: inj

  - pin: 42
    id: TLE8888_PIN_4
    class: outputs
    color: brown
    function: Injector 4
    ts_name: 42 - Injector 4
    type: inj

  # TLE8888 half bridges (pushpull, lowside, or high-low) TLE8888_OUT24
  - pin: 43
    id: TLE8888_PIN_24
    class: outputs
    color: brown
    function: (IDLE stepper coil 2+)
    ts_name: 43 - GP Out 4
    type: [gp_low, gp_pp]

  - pin: 44
    function: TPS sensor supply
    type: 5v
    color: brown left

  - pin: 45
    id: C6
    class: event_inputs
    color: light green right
    function: Crank VR+/hall
    ts_name: 45 - VR/Hall Crank
    type: vr hall

  - pin: 46
    function: Crank VR- (do not connect if hall)
    type: vr
    color: light green

  - pin: 47
    function: CAN bus Low
    type: can
    color: light green

  - pin: 48
    function: CAN bus High
    type: can
    color: light green

info:
  title: microRusEFI
  name: Main Connector
  board_url: https://rusefi.com/s/microrusefi
  directory: microrusefi
  cid: main
  order: 0
  image:
    file: main.jpg
  pins:
    - pin: 1
      x: 1508
      y: 958
    - pin: 2
      x: 1508
      y: 787
    - pin: 3
      x: 1508
      y: 616
    - pin: 4
      x: 1508
      y: 445
    - pin: 5
      x: 1363
      y: 958
    - pin: 6
      x: 1363
      y: 787
    - pin: 7
      x: 1363
      y: 616
    - pin: 8
      x: 1363
      y: 445
    - pin: 9
      x: 1217
      y: 958
    - pin: 10
      x: 1217
      y: 787
    - pin: 11
      x: 1217
      y: 616
    - pin: 12
      x: 1217
      y: 445
    - pin: 13
      x: 1114
      y: 958
    - pin: 14
      x: 1114
      y: 787
    - pin: 15
      x: 1114
      y: 616
    - pin: 16
      x: 1114
      y: 445
    - pin: 17
      x: 1011
      y: 958
    - pin: 18
      x: 1011
      y: 787
    - pin: 19
      x: 1011
      y: 616
    - pin: 20
      x: 1011
      y: 445
    - pin: 21
      x: 908
      y: 958
    - pin: 22
      x: 908
      y: 787
    - pin: 23
      x: 908
      y: 616
    - pin: 24
      x: 908
      y: 445
    - pin: 25
      x: 805
      y: 958
    - pin: 26
      x: 805
      y: 787
    - pin: 27
      x: 805
      y: 616
    - pin: 28
      x: 805
      y: 445
    - pin: 29
      x: 702
      y: 958
    - pin: 30
      x: 702
      y: 787
    - pin: 31
      x: 702
      y: 616
    - pin: 32
      x: 702
      y: 445
    - pin: 33
      x: 599
      y: 958
    - pin: 34
      x: 599
      y: 787
    - pin: 35
      x: 599
      y: 616
    - pin: 36
      x: 599
      y: 445
    - pin: 37
      x: 496
      y: 958
    - pin: 38
      x: 496
      y: 787
    - pin: 39
      x: 496
      y: 616
    - pin: 40
      x: 496
      y: 445
    - pin: 41
      x: 393
      y: 958
    - pin: 42
      x: 393
      y: 787
    - pin: 43
      x: 393
      y: 616
    - pin: 44
      x: 393
      y: 445
    - pin: 45
      x: 290
      y: 958
    - pin: 46
      x: 290
      y: 787
    - pin: 47
      x: 290
      y: 616
    - pin: 48
      x: 290
      y: 445
