meta: config/boards/hellen_mm100_meta.h

pins:
  - pin: B1
    meta: MM100_INJ6
    class: outputs
    type: ls
    ts_name: ___ injector output 6

  - pin: B2
    meta: MM100_INJ5
    class: outputs
    type: ls
    ts_name: ___ injector output 5

  - pin: B3
    meta: MM100_INJ4
    class: outputs
    type: ls
    ts_name: ___ injector output 4

  - pin: B4
    meta: MM100_INJ3
    class: outputs
    type: ls
    ts_name: ___ injector output 3

  - pin: B5
    meta: MM100_INJ2
    class: outputs
    type: ls
    ts_name: ___ injector output 2

  - pin: B6
    meta: MM100_INJ1
    class: outputs
    type: ls
    ts_name: ___ injector output 1

  - pin: B7
    meta: MM100_INJ7
    class: outputs
    type: ls
    ts_name: ___ Low Side output 1

  - pin: B8
    meta: MM100_IGN8
    class: outputs
    type: ls
    ts_name: ___ Fan Relay Weak Low Side output 2

  - pin: B9
    meta: MM100_IGN7
    class: outputs
    type: ls
    ts_name: ___ Main Relay Weak Low Side output 1

  - pin: B10
    meta: MM100_IGN6
    class: outputs
    type: ign
    ts_name: ___ Coil 6

  - pin: B11
    meta: MM100_IGN4
    class: outputs
    type: ign
    ts_name: ___ Coil 4

  - pin: B12
    meta: MM100_IGN3
    class: outputs
    type: ign
    ts_name: ___ Coil 3

  - pin: B13
    meta: MM100_IGN5
    class: outputs
    type: ign
    ts_name: ___ Coil 5

  - pin: B14
    meta: MM100_IGN2
    class: outputs
    type: ign
    ts_name: ___ Coil 2

  - pin: B15
    meta: MM100_IGN1
    class: outputs
    type: ign
    ts_name: ___ Coil 1

  - pin: B16
    meta: MM100_OUT_PWM2
    class: outputs
    type: ls
    ts_name: ___ Low Side output 4

  - pin: B17
    meta: MM100_OUT_PWM1
    class: outputs
    type: ls
    ts_name: ___ Low Side output 3

  - pin: B18
    meta: MM100_INJ8
    class: outputs
    type: ls
    ts_name: ___ Low Side output 2

info:
  cid: b
  title: uaefi
  directory: hellen/uaefi
  board_url: https://github.com/rusefi/rusefi/wiki/uaefi
