meta: config/boards/hellen_mm100_meta.h

pins:
  - pin: B1
    meta: MM100_INJ6
    class: outputs
    type: ls
    color: grey
    ts_name: ___ injector output 6

  - pin: B2
    meta: MM100_INJ5
    class: outputs
    type: ls
    color: yellow
    ts_name: ___ injector output 5

  - pin: B3
    meta: MM100_INJ4
    class: outputs
    type: ls
    ts_name: ___ injector output 4
    color: orange/brown

  - pin: B4
    meta: MM100_INJ3
    class: outputs
    type: ls
    color: blue
    ts_name: ___ injector output 3

  - pin: B5
    meta: MM100_INJ2
    class: outputs
    type: ls
    color: white
    ts_name: ___ injector output 2

  - pin: B6
    meta: MM100_INJ1
    class: outputs
    type: ls
    color: green
    ts_name: ___ injector output 1

  - pin: B7
    meta: MM100_INJ7
    class: outputs
    color: orange
    type: ls
    ts_name: ___ VVT1 or Low Side output 1 (has flyback D2)

  - pin: B8
    meta: MM100_IGN8
    class: outputs
    type: ls
    color: red
    ts_name: ___ Fan Relay Weak Low Side output 2 (no flyback here)

  - pin: B9
    meta: MM100_IGN7
    class: outputs
    type: ls
    color: grey
    ts_name: ___ Main Relay Weak Low Side output 1 (no flyback here)

  - pin: B10
    meta: MM100_IGN6
    class: outputs
    type: ign
    color: grey
    ts_name: ___ Coil 6
    function: coil 6 (5v)

  - pin: B11
    meta: MM100_IGN4
    class: outputs
    type: ign
    color: orange/brown
    ts_name: ___ Coil 4

  - pin: B12
    meta: MM100_IGN3
    class: outputs
    type: ign
    color: blue
    ts_name: ___ Coil 3

  - pin: B13
    meta: MM100_IGN5
    class: outputs
    type: ign
    color: yellow
    ts_name: ___ Coil 5

  - pin: B14
    meta: MM100_IGN2
    class: outputs
    type: ign
    color: white
    ts_name: ___ Coil 2

  - pin: B15
    meta: MM100_IGN1
    class: outputs
    type: ign
    color: green
    ts_name: ___ Coil 1
    function: coil 1 (5v)

  - pin: B16
    meta: MM100_OUT_PWM2
    class: outputs
    type: ls
    color: white
    ts_name: ___ Low Side output 4 / Fuel Pump Relay (has flyback D5)

  - pin: B17
    meta: MM100_OUT_PWM1
    class: outputs
    color: yellow
    type: ls
    ts_name: ___ Low Side output 3 or injector 7 (has flyback D4)

  - pin: B18
    meta: MM100_INJ8
    class: outputs
    color: grey
    type: ls
    ts_name: ___ VVT2 or Idle or Low Side output 2 or injector 8 (has flyback D3)

info:
  cid: b
  title: uaefi
  directory: hellen/uaefi
  board_url: https://wiki.rusefi.com/uaefi
  image:
    file: uaefi-B.jpg
  pins:
    - pin: B1
      x: 927
      y: 230
    - pin: B2
      x: 821
      y: 230
    - pin: B3
      x: 719
      y: 230
    - pin: B4
      x: 615
      y: 230
    - pin: B5
      x: 518
      y: 230
    - pin: B6
      x: 415
      y: 230
    - pin: B7
      x: 315
      y: 230
    - pin: B8
      x: 208
      y: 230
    - pin: B9
      x: 109
      y: 230
    - pin: B10
      x: 927
      y: 130
    - pin: B11
      x: 821
      y: 130
    - pin: B12
      x: 719
      y: 130
    - pin: B13
      x: 615
      y: 130
    - pin: B14
      x: 518
      y: 130
    - pin: B15
      x: 415
      y: 130
    - pin: B16
      x: 315
      y: 130
    - pin: B17
      x: 208
      y: 130
    - pin: B18
      x: 109
      y: 130
