meta: config/boards/hellen_mm100_meta.h

pins:
  - pin: D1
    id: [MM100_IN_O2S_ANALOG, MM100_IN_O2S, MM100_IN_O2S]
    class: [analog_inputs, switch_inputs, event_inputs]
    color: orange
    ts_name: ___ AUX1
    type: av
    function: Auxiliary analog input 1 PullDown 500K

  - pin: D2
    id: [MM100_IN_CRANK_ANALOG, MM100_IN_CRANK, MM100_IN_CRANK]
    class: [analog_inputs, switch_inputs, event_inputs]
    color: yellow
    ts_name: ___ BUTTON1
    function: Button input 1 PullDown 10K

  - pin: D3
    function: Sensor +5v Power Feed
    color: red
    type: 5v

  - pin: D4
    function: Sensor +5v Power Feed
    color: red
    type: 5v

  - pin: D5
    meta: MM100_IN_VSS
    class: event_inputs
    ts_name: ___ FLEX
    color: orange
    function: Flex input (10K PU)

  - pin: D6
    meta: MM100_IN_PPS_ANALOG
    class: analog_inputs
    ts_name: ___ PPS1
    function: Universal analog input. Suggested PPS input 1
    type: av
    color: white

  - pin: D7
    function: CAN1 bus high
    color: green
    type: can

  - pin: D8
    function: CAN1 bus low
    color: blue
    type: can

  - pin: D9
    meta: MM100_IN_MAP1_ANALOG
    class: analog_inputs
    ts_name: ___ MAP
    function: Universal analog input. Suggested MAP input
    type: av
    color: yellow

  - pin: D10
    id: [MM100_IN_CAM_ANALOG, MM100_IN_CAM, MM100_IN_CAM]
    class: [analog_inputs, switch_inputs, event_inputs]
    color: green
    ts_name: ___ A/C Request / BUTTON2
    function: A/C Request / Button input 2 PullDown 10K

  - pin: D11
    color: black
    function: Sensor ground

  - pin: D12
    color: black
    function: Sensor ground

  - pin: D13
    meta: MM100_IN_TPS_ANALOG
    class: analog_inputs
    ts_name: ___ TPS1
    function: Universal analog input. Suggested TPS input 1
    type: av
    color: green

  - pin: D14
    color: yellow
    function: Knock Input (other sensor pin goes to analog ground)

  - pin: D15
    meta: MM100_IN_IAT_ANALOG
    class: analog_inputs
    ts_name: ___ IAT
    function: IAT input
    type: at
    color: blue

  - pin: D16
    meta: MM100_IN_CLT_ANALOG
    class: analog_inputs
    ts_name: ___ CLT Coolant
    function: CLT input
    type: at
    color: grey

info:
  cid: d
  title: uaefi
  directory: hellen/uaefi
  board_url: https://wiki.rusefi.com/uaefi
  image:
    file: uaefi-D.jpg
  pins:
    - pin: D1
      x: 977
      y: 250
    - pin: D2
      x: 862
      y: 250
    - pin: D3
      x: 743
      y: 250
    - pin: D4
      x: 626
      y: 250
    - pin: D5
      x: 511
      y: 250
    - pin: D6
      x: 393
      y: 250
    - pin: D7
      x: 276
      y: 250
    - pin: D8
      x: 160
      y: 250
    - pin: D9
      x: 977
      y: 134
    - pin: D10
      x: 862
      y: 134
    - pin: D11
      x: 743
      y: 134
    - pin: D12
      x: 626
      y: 134
    - pin: D13
      x: 511
      y: 134
    - pin: D14
      x: 393
      y: 134
    - pin: D15
      x: 276
      y: 134
    - pin: D16
      x: 160
      y: 134
