#
# See https://wiki.rusefi.com/Connector-Mapping
#

name: Check Interactive Pinouts

on:
  pull_request:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 2

    - name: Check for Pinout Changes
      run: |
        DIFF=$(git diff --name-only --diff-filter=ACMR HEAD^..HEAD | grep -e "connectors/.*\.yaml"; true)
        echo "CHANGED<<DELIM" >> $GITHUB_ENV
        echo "$DIFF" >> $GITHUB_ENV
        echo "DELIM" >> $GITHUB_ENV

    - name: Generate Pinouts
      uses: chuckwagoncomputing/interactive-pinout@2.16
      with:
        mapping-path: ${{ env.CHANGED }}
        warnings: "notice"
        warning-no-connectors: "false"
        warning-dupe: "error"
        columns: |
          {
          "pin":"Pin Number",
          "ts_name":"TS Name",
          "type":"Type",
          "function":"Typical Function",
          "color":"Pigtail Color"
          }
        print-columns: |
          [
          "function"
          ]
        info-column: "type"
        colors: |
          {
          "12v":"yellow";
          "12V":"yellow";
          "5v":"red",
          "5V":"red",
          "at":"green",
          "av":"brown",
          "can":"blue",
          "din":"lime",
          "etb":"darkcyan",
          "gnd":"darkgreen",
          "gp_high":"aqua",
          "gp_low":"aquamarine",
          "gp_pp":"cyan",
          "hall":"darkolivegreen",
          "hl":"gold",
          "hs":"indigo",
          "ign":"magenta",
          "inj":"maroon",
          "ls":"lightgreen",
          "mr":"firebrick",
          "pgnd":"coral",
          "sgnd":"olive",
          "usb":"lightseagreen",
          "vr":"sienna"
          }
