#
#
#

name: Update rusEFI Reference

on:
  workflow_call:

jobs:
  update-git:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Git Checkout Submodules
        run: |
          git submodule update --init --depth=1 ext/rusefi

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Fetch remote lts-* branches of rusefi submodule
        working-directory: ext/rusefi
        run: |
          git fetch --depth=1 origin '+refs/heads/lts-*:refs/remotes/origin/lts-*'
          git branch -r

      - name: Git Update Submodules
        run: |
          git submodule update --remote

      - name: Commit fresh 'ext/rusefi' submodule
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub git update Action"
          git add ext/rusefi
          OUT=$(git commit -am "GHA says update ext/rusefi submodule" 2>&1) || echo "commit failed, finding out why"
          if echo "$OUT" | grep 'nothing to commit'; then
            echo "submodule: looks like nothing to commit"
            echo "NOCOMMIT=true" >> $GITHUB_ENV
            exit 0
          elif echo "$OUT" | grep 'changed'; then
            echo "submodule: looks like something has changed"
          else
            echo "submodule: looks like something unexpected"
            exit 1
          fi
          git status

      - name: Push
        if: ${{ env.NOCOMMIT != 'true'}}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token }}
          branch: ${{ github.ref }}
