name: Generate Kicad Diffs

on:
  push:
    paths:
    - 'hardware/**'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install sshpass, kicad, and tk bindings
      run: |
        sudo sed -i 's/azure\.//' /etc/apt/sources.list
        sudo add-apt-repository --yes ppa:kicad/kicad-6.0-releases
        sudo apt-get -o Acquire::Retries=3 update
        sudo apt-get install sshpass kicad python3-pip python3-tk scour librsvg2-bin
        pip install python-dateutil pygubu

    - name: Get KiCad-Diff
      run: git clone https://github.com/leoheck/KiCad-Diff.git

    - name: Set SSH variables
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: |
        if [ "${{github.event_name}}" = "push" ] && [ "${{github.ref}}" = "refs/heads/master" ]; then
          echo "::set-env name=RUSEFI_SSH_SERVER::${{secrets.RUSEFI_SSH_SERVER}}";
          echo "::set-env name=RUSEFI_SSH_USER::${{secrets.RUSEFI_SSH_USER}}";
          echo "::set-env name=RUSEFI_SSH_PASS::${{secrets.RUSEFI_SSH_PASS}}";
        fi

    - name: Generate diffs
      working-directory: ./hardware
      run: bash ./rusefi_lib/generate_diffs.sh
