name: Generate Kicad Diffs

on:
  push:
    paths:
    - 'hardware/**'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install lftp, kicad, and tk bindings
      run: |
        sudo add-apt-repository ppa:js-reynaud/kicad-5.1
        sudo apt-get update
        sudo apt-get install lftp kicad python3-tk

    - name: Get KiCad-Diff
      run: git clone https://github.com/chuckwagoncomputing/KiCad-Diff.git

    - name: Set FTP variables
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: |
        if [ "${{github.event_name}}" = "push" ] && [ "${{github.ref}}" = "refs/heads/master" ]; then
          echo "::set-env name=RUSEFI_FTP_SERVER::${{secrets.RUSEFI_FTP_SERVER}}";
          echo "::set-env name=RUSEFI_DOXYGEN_FTP_USER::${{secrets.RUSEFI_DOXYGEN_FTP_USER}}";
          echo "::set-env name=RUSEFI_DOXYGEN_FTP_PASS::${{secrets.RUSEFI_DOXYGEN_FTP_PASS}}";
        fi

    - name: Generate diffs
      working-directory: ./hardware
      run: bash ./rusefi_lib/generate_diffs.sh
